/* correcciones_tecnicas.js — Biblioteca de correcciones técnico-tácticas (nivel elite).
   Editable: sumá/quitá items acá o desde el Plan de Desarrollo (modo editor).
   Estructura: window.CORRECCIONES = { <fundamento>: [ {t:"texto", c:"categoría"}, ... ] }
   Categorías: Técnica · Táctica · Lectura · Físico/Coordinación · Mental        */
window.CORRECCIONES = {
  "saque": [
    {t:"Flotado: contacto seco en el centro de la pelota, sin acompañar, muñeca firme y bloqueada.", c:"Técnica"},
    {t:"Flotado: lanzamiento bajo, adelante y a la misma altura siempre, sin efecto.", c:"Técnica"},
    {t:"Flotado: brazo de armado alto y quieto (\u201ccongelado\u201d) antes del contacto.", c:"Técnica"},
    {t:"Flotado: contacto delante del cuerpo, no encima de la cabeza.", c:"Técnica"},
    {t:"Salto: lanzamiento consistente adelante, a la altura del ataque en carrera.", c:"Técnica"},
    {t:"Salto: últimos dos pasos en aceleración, no frenar la carrera antes de despegar.", c:"Físico/Coordinación"},
    {t:"Salto: contacto arriba y adelante con látigo de muñeca (topspin) para bajar la pelota.", c:"Técnica"},
    {t:"Armar el brazo en \u201carco y flecha\u201d, codo alto y atrás.", c:"Técnica"},
    {t:"Elegir la zona antes de lanzar: mirar el sistema de recepción rival.", c:"Táctica"},
    {t:"Atacar zonas de conflicto: entre dos receptores, cuerpo, o zonas 1 y 5.", c:"Táctica"},
    {t:"Buscar al receptor más débil o al que rota a atacar (romperle el approach).", c:"Táctica"},
    {t:"Saque corto para sacar al armador de la red y romper el K1 rival.", c:"Táctica"},
    {t:"Variar ritmo, altura y zona según cómo está parada la recepción.", c:"Táctica"},
    {t:"Rutina previa fija (respiración + botar) para estabilizar bajo presión.", c:"Mental"},
    {t:"Bajo presión: priorizar consistencia y zona antes que potencia máxima.", c:"Mental"},
    {t:"Leer la salida de la mano del rival no aplica: acá VOS marcás el ritmo, jugá tu saque.", c:"Mental"}
  ],
  "recepcion": [
    {t:"En flotado, abrir la cadera y recibir de costado para poder empujar mejor.", c:"Técnica"},
    {t:"Plataforma formada antes de que la pelota cruce la red.", c:"Técnica"},
    {t:"Meter el cuerpo detrás de la pelota, no estirar los brazos al costado.", c:"Técnica"},
    {t:"Ángulo de plataforma y hombros apuntando al blanco (zona 2-3).", c:"Técnica"},
    {t:"Peso adelante y piernas flexionadas, listo para avanzar, nunca retroceder.", c:"Técnica"},
    {t:"Flotante: absorber bajando la plataforma en el contacto, no golpear.", c:"Técnica"},
    {t:"Saque potente: plataforma firme y ceder con los hombros.", c:"Técnica"},
    {t:"No recibir por encima de la línea de los hombros (usar dedos si viene alta).", c:"Técnica"},
    {t:"Primer paso explosivo a la pelota, después ajustar con pasos cortos.", c:"Físico/Coordinación"},
    {t:"Recuperar el balance tras el contacto para entrar a atacar (transición R-A).", c:"Físico/Coordinación"},
    {t:"Leer el brazo y la salida de mano del sacador para arrancar temprano.", c:"Lectura"},
    {t:"Reconocer flotado vs. potencia por el approach del sacador y ajustar la base.", c:"Lectura"},
    {t:"Llamar la pelota temprano y fuerte; dividir el campo con el compañero.", c:"Táctica"},
    {t:"Definir zonas de responsabilidad según la rotación (quién toma el centro).", c:"Táctica"},
    {t:"Contra un buen sacador, achicar objetivo: pase seguro y alto al centro.", c:"Mental"}
  ],
  "armado": [
    {t:"Llevar los pies al balón: armar de piernas, no solo de brazos.", c:"Técnica"},
    {t:"Contacto arriba de la frente, ventana con pulgares e índices en triángulo.", c:"Técnica"},
    {t:"Empuje simultáneo de piernas, tronco y muñecas (cadena cinética).", c:"Técnica"},
    {t:"Llegar en equilibrio: pies antes que la pelota, contactar quieto.", c:"Técnica"},
    {t:"Hombros cuadrados y neutros para no delatar la dirección del pase.", c:"Técnica"},
    {t:"Colocar el cuerpo de perfil al blanco para engañar al bloqueo.", c:"Técnica"},
    {t:"Back set sin cambiar el ritmo ni la postura respecto del frontal.", c:"Técnica"},
    {t:"Ajustar la altura del pase al tiempo/conexión de cada atacante.", c:"Técnica"},
    {t:"Pase lejos de la red: priorizar altura y separación del net.", c:"Técnica"},
    {t:"Leer el bloqueo: armar al lado del bloqueador lento o al 1x1.", c:"Lectura"},
    {t:"Reconocer la calidad de recepción y decidir tempo en consecuencia.", c:"Lectura"},
    {t:"Recepción perfecta: activar el rápido / segunda intención al central.", c:"Táctica"},
    {t:"Distribuir para romper el bloqueo: alternar tempos y zonas.", c:"Táctica"},
    {t:"Involucrar al zaguero (pipe/zona 1) para descomprimir las puntas.", c:"Táctica"},
    {t:"Comunicar sistema y corrido antes de cada punto.", c:"Táctica"},
    {t:"Bajo presión: asegurar un balón atacable antes de arriesgar el rápido.", c:"Mental"}
  ],
  "ataque": [
    {t:"Levantar la mano izquierda e ir hacia la pelota, no esperarla.", c:"Técnica"},
    {t:"Último paso largo y de freno para transformar la carrera en salto vertical.", c:"Técnica"},
    {t:"Carrera en aceleración (pasos cortos a largos): no llegar frenado.", c:"Físico/Coordinación"},
    {t:"Armado del brazo \u201carco y flecha\u201d: codo alto y atrás, no brazo bajo.", c:"Técnica"},
    {t:"Contactar arriba y adelante, en el punto más alto del salto.", c:"Técnica"},
    {t:"Látigo de muñeca (topspin) para bajar la pelota dentro de la cancha.", c:"Técnica"},
    {t:"Balancear los dos brazos en el despegue para ganar altura.", c:"Físico/Coordinación"},
    {t:"Aterrizar equilibrado para transicionar rápido a defensa/re-ataque.", c:"Físico/Coordinación"},
    {t:"Ver el bloqueo en el aire y decidir: potencia, dirección o finta/\u201ctool\u201d.", c:"Lectura"},
    {t:"Usar el bloqueo (mano afuera) cuando está bien armado.", c:"Táctica"},
    {t:"Leer la defensa/piso y elegir diagonal larga o línea.", c:"Lectura"},
    {t:"Ajustar el approach a la calidad del pase (pase separado: esperar y potencia).", c:"Lectura"},
    {t:"Cambio de ritmo: rodada o finta cuando el bloqueo salta bien.", c:"Táctica"},
    {t:"Pelota alta/rota: priorizar buen contacto y colocación, no fuerza.", c:"Táctica"},
    {t:"Repetir el approach igual siempre para no delatar el tiempo.", c:"Mental"}
  ],
  "bloqueo": [
    {t:"Penetrar las manos al campo rival, no bloquear vertical.", c:"Técnica"},
    {t:"Saltar después del atacante (timing), no simultáneo, para tapar el contacto.", c:"Técnica"},
    {t:"Manos firmes, dedos abiertos y pulgares arriba, tapando la pelota.", c:"Técnica"},
    {t:"Manos por encima de la red el mayor tiempo posible, no atrás.", c:"Técnica"},
    {t:"Desplazamiento con paso cruzado o de patinador y cerrar cuadrado al net.", c:"Físico/Coordinación"},
    {t:"Cerrar el bloqueo (dos manos juntas) sin dejar hueco entre bloqueadores.", c:"Técnica"},
    {t:"Caer equilibrado tras bloquear y transicionar a defensa/ataque.", c:"Físico/Coordinación"},
    {t:"Leer la zona y las manos del armador antes que la pelota.", c:"Lectura"},
    {t:"No saltar al primer engaño: leer el brazo del atacante.", c:"Lectura"},
    {t:"Central: salir al tiempo del rápido con pies cuadrados, leyendo al armador.", c:"Técnica"},
    {t:"Puntas: paciencia, no adelantar el salto, cerrar hacia el centro.", c:"Táctica"},
    {t:"Tomar diagonal o línea según el sistema defensivo acordado.", c:"Táctica"},
    {t:"Tapar la mano/zona fuerte del atacante según el scouting.", c:"Táctica"},
    {t:"Comunicar quién cierra y quién toma el rápido antes del punto.", c:"Táctica"}
  ],
  "defensa": [
    {t:"Parar y armar la base antes del contacto del atacante (split step).", c:"Técnica"},
    {t:"No caer al piso anticipado: esperar con base baja y peso adelante.", c:"Técnica"},
    {t:"Base defensiva: piernas más anchas que los hombros, manos afuera y adelante.", c:"Técnica"},
    {t:"Defender delante del cuerpo, brazos al frente, no al costado.", c:"Técnica"},
    {t:"Absorber/redirigir al centro (zona 2-3) para reconstruir el ataque.", c:"Técnica"},
    {t:"Digs altos y al centro para dar tiempo a la reconstrucción.", c:"Técnica"},
    {t:"Leer al atacante (brazo, cuerpo) y qué zona tapa el bloqueo.", c:"Lectura"},
    {t:"Posicionarse según lo que deja libre el bloqueo (defender el hueco).", c:"Lectura"},
    {t:"Pelota de finta: arrancar bajo y hacia adelante, no quedarse plantado.", c:"Físico/Coordinación"},
    {t:"Perseguir la pelota con el cuerpo, dar siempre el segundo paso.", c:"Físico/Coordinación"},
    {t:"Cubrir al bloqueo en los rebotes cortos (coberturas).", c:"Táctica"},
    {t:"Convertir la defensa en contraataque: primer pase jugable al armador.", c:"Táctica"},
    {t:"Comunicar en voz alta antes y durante la jugada (\u201ctoco\u201d, \u201cmía\u201d, \u201cfuera\u201d).", c:"Mental"}
  ]
};
