window.HISTORIAL_DATA = {
  "generado": "24/05/2026 18:43:53",
  "entrenamientos": [
    {
        "fecha": "01/05/2026",
        "tipo": "P",
        "rival": "UNTREF",
        "resultado": {
            "casla": 3,
            "rival": 1,
            "sets": [
                "22-25",
                "25-16",
                "25-14",
                "25-22"
            ]
        },
        "jugadores": [
            {
                "c": 2,
                "n": "OJUEZ",
                "sT": 7,
                "sEff": -7,
                "sPunto": 0,
                "sPos": 2,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 4,
                "sErr": 1,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 10,
                "aEff": 50,
                "aPunto": 6,
                "aPos": 1,
                "aAdm": 0,
                "aNeg": 2,
                "aVend": 1,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 4,
                "bPt": 1,
                "bPtPos": 1,
                "dv4": {
                    "J4": {
                        "tot": 3,
                        "pt": 2,
                        "err": 0,
                        "orig": 3,
                        "dest": "6"
                    },
                    "J1": {
                        "tot": 2,
                        "pt": 1,
                        "err": 0,
                        "orig": 3,
                        "dest": "8"
                    },
                    "V3": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 0,
                        "dest": ""
                    },
                    "W2": {
                        "tot": 1,
                        "pt": 0,
                        "err": 0,
                        "orig": 2,
                        "dest": "4"
                    },
                    "J2": {
                        "tot": 2,
                        "pt": 1,
                        "err": 0,
                        "orig": 3,
                        "dest": "6"
                    },
                    "J3": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 0,
                        "dest": ""
                    }
                },
                "bEff": 50
            },
            {
                "c": 3,
                "n": "WINER",
                "sT": 0,
                "sEff": 0,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 0,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 31,
                "rEff": 18,
                "rPunto": 5,
                "rPos": 7,
                "rAdm": 9,
                "rNeg": 5,
                "rVend": 4,
                "rErr": 1,
                "aT": 0,
                "aEff": 0,
                "aPunto": 0,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 0,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {}
            },
            {
                "c": 4,
                "n": "VAZQUEZ",
                "sT": 1,
                "sEff": 0,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 1,
                "sNeg": 0,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 0,
                "aEff": 0,
                "aPunto": 0,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 0,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {}
            },
            {
                "c": 5,
                "n": "RAMOS",
                "sT": 19,
                "sEff": -17,
                "sPunto": 3,
                "sPos": 1,
                "sVend": 1,
                "sAdm": 2,
                "sNeg": 5,
                "sErr": 7,
                "sOrig": "",
                "sDest": "",
                "rT": 1,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 1,
                "rVend": 0,
                "rErr": 0,
                "aT": 31,
                "aEff": 35,
                "aPunto": 16,
                "aPos": 4,
                "aAdm": 2,
                "aNeg": 4,
                "aVend": 3,
                "aErr": 2,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 17,
                "bPt": 1,
                "bPtPos": 2,
                "dv4": {
                    "G2": {
                        "tot": 6,
                        "pt": 2,
                        "err": 0,
                        "orig": 2,
                        "dest": "1"
                    },
                    "W2": {
                        "tot": 13,
                        "pt": 8,
                        "err": 1,
                        "orig": 2,
                        "dest": "4"
                    },
                    "G9": {
                        "tot": 4,
                        "pt": 2,
                        "err": 0,
                        "orig": 9,
                        "dest": "1"
                    },
                    "Y9": {
                        "tot": 8,
                        "pt": 4,
                        "err": 1,
                        "orig": 0,
                        "dest": ""
                    }
                },
                "bEff": 18
            },
            {
                "c": 9,
                "n": "GODOY",
                "sT": 18,
                "sEff": -8,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 1,
                "sAdm": 4,
                "sNeg": 11,
                "sErr": 2,
                "sOrig": "",
                "sDest": "",
                "rT": 2,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 1,
                "rNeg": 1,
                "rVend": 0,
                "rErr": 0,
                "aT": 1,
                "aEff": 100,
                "aPunto": 1,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 12,
                "bPt": 1,
                "bPtPos": 6,
                "dv4": {
                    "JJ": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 0,
                        "dest": ""
                    }
                },
                "bEff": 58
            },
            {
                "c": 11,
                "n": "DURDOS",
                "sT": 17,
                "sEff": -25,
                "sPunto": 2,
                "sPos": 1,
                "sVend": 1,
                "sAdm": 4,
                "sNeg": 2,
                "sErr": 7,
                "sOrig": "",
                "sDest": "",
                "rT": 13,
                "rEff": 69,
                "rPunto": 7,
                "rPos": 4,
                "rAdm": 1,
                "rNeg": 1,
                "rVend": 0,
                "rErr": 0,
                "aT": 30,
                "aEff": 37,
                "aPunto": 14,
                "aPos": 1,
                "aAdm": 3,
                "aNeg": 9,
                "aVend": 0,
                "aErr": 3,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 9,
                "bPt": 1,
                "bPtPos": 4,
                "dv4": {
                    "G4": {
                        "tot": 11,
                        "pt": 4,
                        "err": 2,
                        "orig": 4,
                        "dest": "2"
                    },
                    "W4": {
                        "tot": 15,
                        "pt": 9,
                        "err": 0,
                        "orig": 0,
                        "dest": ""
                    },
                    "Y8": {
                        "tot": 4,
                        "pt": 1,
                        "err": 1,
                        "orig": 8,
                        "dest": "6"
                    }
                },
                "bEff": 56
            },
            {
                "c": 13,
                "n": "ROJAS CARUSO",
                "sT": 1,
                "sEff": 0,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 1,
                "sNeg": 0,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 2,
                "rEff": 50,
                "rPunto": 1,
                "rPos": 0,
                "rAdm": 1,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 0,
                "aEff": 0,
                "aPunto": 0,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 0,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {}
            },
            {
                "c": 14,
                "n": "NIELSON",
                "sT": 14,
                "sEff": -7,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 6,
                "sNeg": 7,
                "sErr": 1,
                "sOrig": "",
                "sDest": "",
                "rT": 15,
                "rEff": 53,
                "rPunto": 4,
                "rPos": 8,
                "rAdm": 3,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 27,
                "aEff": 33,
                "aPunto": 11,
                "aPos": 4,
                "aAdm": 3,
                "aNeg": 7,
                "aVend": 1,
                "aErr": 1,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 3,
                "bPt": 1,
                "bPtPos": 0,
                "dv4": {
                    "G4": {
                        "tot": 9,
                        "pt": 2,
                        "err": 0,
                        "orig": 4,
                        "dest": "4"
                    },
                    "W4": {
                        "tot": 17,
                        "pt": 8,
                        "err": 1,
                        "orig": 4,
                        "dest": "1"
                    },
                    "V3": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 0,
                        "dest": ""
                    }
                },
                "bEff": 33
            },
            {
                "c": 15,
                "n": "ROTEZZI",
                "sT": 13,
                "sEff": 10,
                "sPunto": 1,
                "sPos": 1,
                "sVend": 0,
                "sAdm": 1,
                "sNeg": 10,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 9,
                "aEff": 56,
                "aPunto": 6,
                "aPos": 1,
                "aAdm": 1,
                "aNeg": 0,
                "aVend": 0,
                "aErr": 1,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 5,
                "bPt": 1,
                "bPtPos": 2,
                "dv4": {
                    "J1": {
                        "tot": 6,
                        "pt": 3,
                        "err": 1,
                        "orig": 3,
                        "dest": "9"
                    },
                    "J4": {
                        "tot": 3,
                        "pt": 3,
                        "err": 0,
                        "orig": 3,
                        "dest": "6"
                    }
                },
                "bEff": 60
            },
            {
                "c": 17,
                "n": "HERBSOMMER",
                "sT": 1,
                "sEff": 0,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 1,
                "sNeg": 0,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 0,
                "aEff": 0,
                "aPunto": 0,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 0,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {}
            },
            {
                "c": 0,
                "n": "TOTALES EQUIPO",
                "sT": 91,
                "sEff": -10,
                "sPunto": 6,
                "sPos": 5,
                "sVend": 3,
                "sAdm": 20,
                "sNeg": 39,
                "sErr": 18,
                "sOrig": "",
                "sDest": "",
                "rT": 64,
                "rEff": 37,
                "rPunto": 17,
                "rPos": 19,
                "rAdm": 15,
                "rNeg": 8,
                "rVend": 4,
                "rErr": 1,
                "aT": 108,
                "aEff": 39,
                "aPunto": 54,
                "aPos": 11,
                "aAdm": 9,
                "aNeg": 22,
                "aVend": 5,
                "aErr": 7,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 50,
                "bPt": 6,
                "bPtPos": 15,
                "dv4": {
                    "G2": {
                        "tot": 6,
                        "pt": 2,
                        "err": 0,
                        "orig": 2,
                        "dest": "1"
                    },
                    "W2": {
                        "tot": 14,
                        "pt": 8,
                        "err": 1,
                        "orig": 2,
                        "dest": "4"
                    },
                    "G4": {
                        "tot": 20,
                        "pt": 6,
                        "err": 2,
                        "orig": 4,
                        "dest": "4"
                    },
                    "J1": {
                        "tot": 8,
                        "pt": 4,
                        "err": 1,
                        "orig": 3,
                        "dest": "9"
                    },
                    "G9": {
                        "tot": 4,
                        "pt": 2,
                        "err": 0,
                        "orig": 9,
                        "dest": "1"
                    },
                    "Y9": {
                        "tot": 8,
                        "pt": 4,
                        "err": 1,
                        "orig": 0,
                        "dest": ""
                    },
                    "J4": {
                        "tot": 6,
                        "pt": 5,
                        "err": 0,
                        "orig": 3,
                        "dest": "6"
                    },
                    "W4": {
                        "tot": 32,
                        "pt": 17,
                        "err": 1,
                        "orig": 4,
                        "dest": "1"
                    },
                    "Y8": {
                        "tot": 4,
                        "pt": 1,
                        "err": 1,
                        "orig": 8,
                        "dest": "6"
                    },
                    "V3": {
                        "tot": 2,
                        "pt": 2,
                        "err": 0,
                        "orig": 0,
                        "dest": ""
                    },
                    "JJ": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 0,
                        "dest": ""
                    },
                    "J2": {
                        "tot": 2,
                        "pt": 1,
                        "err": 0,
                        "orig": 3,
                        "dest": "6"
                    },
                    "J3": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 0,
                        "dest": ""
                    }
                },
                "bEff": 42
            }
        ]
    },
    {
        "fecha": "05/05/2026",
        "tipo": "P",
        "rival": "Ciudad Voley",
        "resultado": {
            "casla": 0,
            "rival": 3,
            "sets": [
                "25-27",
                "16-25",
                "22-25"
            ]
        },
        "jugadores": [
            {
                "c": 2,
                "n": "OJUEZ",
                "sT": 2,
                "sEff": 0,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 2,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 3,
                "aEff": 67,
                "aPunto": 2,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 1,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 5,
                "bPt": 0,
                "bPtPos": 1,
                "dv4": {
                    "J2": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 0,
                        "dest": ""
                    },
                    "J4": {
                        "tot": 2,
                        "pt": 1,
                        "err": 0,
                        "orig": 3,
                        "dest": "6"
                    }
                },
                "bEff": 20
            },
            {
                "c": 3,
                "n": "WINER",
                "sT": 0,
                "sEff": 0,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 0,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 36,
                "rEff": 10,
                "rPunto": 3,
                "rPos": 9,
                "rAdm": 9,
                "rNeg": 10,
                "rVend": 2,
                "rErr": 3,
                "aT": 0,
                "aEff": 0,
                "aPunto": 0,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 0,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {}
            },
            {
                "c": 5,
                "n": "RAMOS",
                "sT": 11,
                "sEff": -20,
                "sPunto": 0,
                "sPos": 3,
                "sVend": 0,
                "sAdm": 2,
                "sNeg": 3,
                "sErr": 3,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 32,
                "aEff": 28,
                "aPunto": 15,
                "aPos": 2,
                "aAdm": 2,
                "aNeg": 7,
                "aVend": 2,
                "aErr": 4,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 10,
                "bPt": 2,
                "bPtPos": 1,
                "dv4": {
                    "W2": {
                        "tot": 10,
                        "pt": 4,
                        "err": 0,
                        "orig": 2,
                        "dest": "9"
                    },
                    "G2": {
                        "tot": 9,
                        "pt": 4,
                        "err": 1,
                        "orig": 0,
                        "dest": ""
                    },
                    "G9": {
                        "tot": 5,
                        "pt": 4,
                        "err": 0,
                        "orig": 9,
                        "dest": "4"
                    },
                    "Y9": {
                        "tot": 8,
                        "pt": 3,
                        "err": 3,
                        "orig": 9,
                        "dest": "5"
                    }
                },
                "bEff": 30
            },
            {
                "c": 9,
                "n": "GODOY",
                "sT": 15,
                "sEff": 10,
                "sPunto": 1,
                "sPos": 2,
                "sVend": 0,
                "sAdm": 1,
                "sNeg": 11,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 1,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 1,
                "rVend": 0,
                "rErr": 0,
                "aT": 0,
                "aEff": 0,
                "aPunto": 0,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 3,
                "bPt": 0,
                "bPtPos": 2,
                "dv4": {},
                "bEff": 67
            },
            {
                "c": 11,
                "n": "DURDOS",
                "sT": 10,
                "sEff": -50,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 1,
                "sNeg": 4,
                "sErr": 5,
                "sOrig": "",
                "sDest": "",
                "rT": 15,
                "rEff": 27,
                "rPunto": 2,
                "rPos": 7,
                "rAdm": 3,
                "rNeg": 1,
                "rVend": 1,
                "rErr": 1,
                "aT": 14,
                "aEff": 50,
                "aPunto": 9,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 3,
                "aVend": 1,
                "aErr": 1,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 2,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {
                    "G4": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 4,
                        "dest": "1"
                    },
                    "Y8": {
                        "tot": 4,
                        "pt": 2,
                        "err": 0,
                        "orig": 8,
                        "dest": "1"
                    },
                    "W4": {
                        "tot": 8,
                        "pt": 5,
                        "err": 1,
                        "orig": 4,
                        "dest": "2"
                    },
                    "V3": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 0,
                        "dest": ""
                    }
                },
                "bEff": 0
            },
            {
                "c": 13,
                "n": "ROJAS CARUSO",
                "sT": 1,
                "sEff": 0,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 1,
                "sNeg": 0,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 2,
                "rEff": 25,
                "rPunto": 0,
                "rPos": 1,
                "rAdm": 1,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 0,
                "aEff": 0,
                "aPunto": 0,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 0,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {}
            },
            {
                "c": 14,
                "n": "NIELSON",
                "sT": 10,
                "sEff": -40,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 1,
                "sNeg": 5,
                "sErr": 4,
                "sOrig": "",
                "sDest": "",
                "rT": 11,
                "rEff": 45,
                "rPunto": 2,
                "rPos": 6,
                "rAdm": 1,
                "rNeg": 2,
                "rVend": 0,
                "rErr": 0,
                "aT": 26,
                "aEff": 15,
                "aPunto": 7,
                "aPos": 2,
                "aAdm": 3,
                "aNeg": 11,
                "aVend": 3,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 6,
                "bPt": 0,
                "bPtPos": 2,
                "dv4": {
                    "W4": {
                        "tot": 13,
                        "pt": 3,
                        "err": 0,
                        "orig": 4,
                        "dest": "7"
                    },
                    "G4": {
                        "tot": 13,
                        "pt": 4,
                        "err": 0,
                        "orig": 4,
                        "dest": "2"
                    }
                },
                "bEff": 33
            },
            {
                "c": 17,
                "n": "HERBSOMMER",
                "sT": 7,
                "sEff": -11,
                "sPunto": 0,
                "sPos": 1,
                "sVend": 0,
                "sAdm": 1,
                "sNeg": 4,
                "sErr": 1,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 2,
                "aEff": 50,
                "aPunto": 1,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 1,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 4,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {
                    "J4": {
                        "tot": 2,
                        "pt": 1,
                        "err": 0,
                        "orig": 3,
                        "dest": "1"
                    }
                },
                "bEff": 0
            },
            {
                "c": 0,
                "n": "TOTALES EQUIPO",
                "sT": 56,
                "sEff": -19,
                "sPunto": 1,
                "sPos": 6,
                "sVend": 0,
                "sAdm": 7,
                "sNeg": 29,
                "sErr": 13,
                "sOrig": "",
                "sDest": "",
                "rT": 65,
                "rEff": 20,
                "rPunto": 7,
                "rPos": 23,
                "rAdm": 14,
                "rNeg": 14,
                "rVend": 3,
                "rErr": 4,
                "aT": 77,
                "aEff": 30,
                "aPunto": 34,
                "aPos": 4,
                "aAdm": 5,
                "aNeg": 23,
                "aVend": 6,
                "aErr": 5,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 30,
                "bPt": 2,
                "bPtPos": 6,
                "dv4": {
                    "W2": {
                        "tot": 10,
                        "pt": 4,
                        "err": 0,
                        "orig": 2,
                        "dest": "9"
                    },
                    "G4": {
                        "tot": 14,
                        "pt": 5,
                        "err": 0,
                        "orig": 4,
                        "dest": "1"
                    },
                    "G2": {
                        "tot": 9,
                        "pt": 4,
                        "err": 1,
                        "orig": 0,
                        "dest": ""
                    },
                    "J2": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 0,
                        "dest": ""
                    },
                    "G9": {
                        "tot": 5,
                        "pt": 4,
                        "err": 0,
                        "orig": 9,
                        "dest": "4"
                    },
                    "W4": {
                        "tot": 21,
                        "pt": 8,
                        "err": 1,
                        "orig": 4,
                        "dest": "7"
                    },
                    "Y8": {
                        "tot": 4,
                        "pt": 2,
                        "err": 0,
                        "orig": 8,
                        "dest": "1"
                    },
                    "J4": {
                        "tot": 4,
                        "pt": 2,
                        "err": 0,
                        "orig": 3,
                        "dest": "6"
                    },
                    "Y9": {
                        "tot": 8,
                        "pt": 3,
                        "err": 3,
                        "orig": 9,
                        "dest": "5"
                    },
                    "V3": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 0,
                        "dest": ""
                    }
                },
                "bEff": 27
            }
        ]
    },
    {
        "fecha": "08/05/2026",
        "tipo": "P",
        "rival": "Ferro",
        "resultado": {
            "casla": 1,
            "rival": 3,
            "sets": [
                "22-25",
                "25-18",
                "17-25",
                "23-25"
            ]
        },
        "jugadores": [
            {
                "c": 2,
                "n": "OJUEZ",
                "sT": 3,
                "sEff": -33,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 2,
                "sErr": 1,
                "sOrig": "",
                "sDest": "",
                "rT": 1,
                "rEff": 100,
                "rPunto": 1,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 5,
                "aEff": 80,
                "aPunto": 4,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 1,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 5,
                "bPt": 5,
                "bPtPos": 0,
                "dv4": {
                    "J1": {
                        "tot": 4,
                        "pt": 3,
                        "err": 0,
                        "orig": 3,
                        "dest": "6"
                    },
                    "J4": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 3,
                        "dest": "3"
                    }
                },
                "bEff": 100
            },
            {
                "c": 4,
                "n": "VAZQUEZ",
                "sT": 6,
                "sEff": 0,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 2,
                "sNeg": 4,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 2,
                "aEff": 100,
                "aPunto": 2,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 2,
                "bPt": 0,
                "bPtPos": 1,
                "dv4": {
                    "JJ": {
                        "tot": 2,
                        "pt": 2,
                        "err": 0,
                        "orig": 2,
                        "dest": "4"
                    }
                },
                "bEff": 50
            },
            {
                "c": 5,
                "n": "RAMOS",
                "sT": 10,
                "sEff": -38,
                "sPunto": 1,
                "sPos": 1,
                "sVend": 0,
                "sAdm": 1,
                "sNeg": 2,
                "sErr": 5,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 27,
                "aEff": -4,
                "aPunto": 8,
                "aPos": 1,
                "aAdm": 2,
                "aNeg": 7,
                "aVend": 5,
                "aErr": 4,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 8,
                "bPt": 0,
                "bPtPos": 1,
                "dv4": {
                    "W2": {
                        "tot": 9,
                        "pt": 2,
                        "err": 2,
                        "orig": 2,
                        "dest": "2"
                    },
                    "G2": {
                        "tot": 6,
                        "pt": 0,
                        "err": 2,
                        "orig": 2,
                        "dest": "1"
                    },
                    "Y9": {
                        "tot": 7,
                        "pt": 3,
                        "err": 0,
                        "orig": 9,
                        "dest": "1"
                    },
                    "G9": {
                        "tot": 4,
                        "pt": 2,
                        "err": 0,
                        "orig": 9,
                        "dest": "4"
                    },
                    "V3": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 0,
                        "dest": ""
                    }
                },
                "bEff": 12
            },
            {
                "c": 9,
                "n": "GODOY",
                "sT": 13,
                "sEff": 13,
                "sPunto": 1,
                "sPos": 3,
                "sVend": 0,
                "sAdm": 2,
                "sNeg": 7,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 1,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 1,
                "rVend": 0,
                "rErr": 0,
                "aT": 2,
                "aEff": -100,
                "aPunto": 0,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 1,
                "aErr": 1,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 6,
                "bPt": 1,
                "bPtPos": 0,
                "dv4": {
                    "JJ": {
                        "tot": 1,
                        "pt": 0,
                        "err": 0,
                        "orig": 2,
                        "dest": "4"
                    },
                    "V3": {
                        "tot": 1,
                        "pt": 0,
                        "err": 1,
                        "orig": 3,
                        "dest": "6"
                    }
                },
                "bEff": 17
            },
            {
                "c": 11,
                "n": "DURDOS",
                "sT": 10,
                "sEff": -32,
                "sPunto": 0,
                "sPos": 3,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 3,
                "sErr": 4,
                "sOrig": "",
                "sDest": "",
                "rT": 28,
                "rEff": 52,
                "rPunto": 10,
                "rPos": 12,
                "rAdm": 3,
                "rNeg": 1,
                "rVend": 1,
                "rErr": 1,
                "aT": 36,
                "aEff": 19,
                "aPunto": 13,
                "aPos": 3,
                "aAdm": 4,
                "aNeg": 10,
                "aVend": 2,
                "aErr": 4,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 7,
                "bPt": 3,
                "bPtPos": 0,
                "dv4": {
                    "W4": {
                        "tot": 23,
                        "pt": 7,
                        "err": 2,
                        "orig": 4,
                        "dest": "5"
                    },
                    "G4": {
                        "tot": 7,
                        "pt": 3,
                        "err": 0,
                        "orig": 4,
                        "dest": "1"
                    },
                    "G8": {
                        "tot": 2,
                        "pt": 1,
                        "err": 1,
                        "orig": 0,
                        "dest": ""
                    },
                    "Y8": {
                        "tot": 2,
                        "pt": 1,
                        "err": 1,
                        "orig": 8,
                        "dest": "6"
                    },
                    "V3": {
                        "tot": 1,
                        "pt": 0,
                        "err": 0,
                        "orig": 3,
                        "dest": "3"
                    },
                    "W3": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 4,
                        "dest": "2"
                    }
                },
                "bEff": 43
            },
            {
                "c": 12,
                "n": "ZANOTTI",
                "sT": 0,
                "sEff": 0,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 0,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 38,
                "rEff": 36,
                "rPunto": 11,
                "rPos": 13,
                "rAdm": 5,
                "rNeg": 4,
                "rVend": 2,
                "rErr": 3,
                "aT": 0,
                "aEff": 0,
                "aPunto": 0,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 0,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {}
            },
            {
                "c": 13,
                "n": "ROJAS CARUSO",
                "sT": 2,
                "sEff": -50,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 1,
                "sErr": 1,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 0,
                "aEff": 0,
                "aPunto": 0,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 0,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {}
            },
            {
                "c": 14,
                "n": "NIELSON",
                "sT": 25,
                "sEff": 12,
                "sPunto": 1,
                "sPos": 6,
                "sVend": 1,
                "sAdm": 8,
                "sNeg": 9,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 12,
                "rEff": 42,
                "rPunto": 6,
                "rPos": 3,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 1,
                "rErr": 2,
                "aT": 22,
                "aEff": 14,
                "aPunto": 7,
                "aPos": 3,
                "aAdm": 3,
                "aNeg": 5,
                "aVend": 2,
                "aErr": 2,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 6,
                "bPt": 1,
                "bPtPos": 1,
                "dv4": {
                    "G4": {
                        "tot": 8,
                        "pt": 3,
                        "err": 0,
                        "orig": 4,
                        "dest": "5"
                    },
                    "W4": {
                        "tot": 13,
                        "pt": 4,
                        "err": 2,
                        "orig": 4,
                        "dest": "1"
                    },
                    "G8": {
                        "tot": 1,
                        "pt": 0,
                        "err": 0,
                        "orig": 8,
                        "dest": "5"
                    }
                },
                "bEff": 33
            },
            {
                "c": 17,
                "n": "HERBSOMMER",
                "sT": 9,
                "sEff": 0,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 9,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 10,
                "aEff": 10,
                "aPunto": 3,
                "aPos": 0,
                "aAdm": 2,
                "aNeg": 3,
                "aVend": 1,
                "aErr": 1,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 8,
                "bPt": 2,
                "bPtPos": 0,
                "dv4": {
                    "J1": {
                        "tot": 6,
                        "pt": 2,
                        "err": 0,
                        "orig": 3,
                        "dest": "3"
                    },
                    "J4": {
                        "tot": 4,
                        "pt": 1,
                        "err": 1,
                        "orig": 3,
                        "dest": "7"
                    }
                },
                "bEff": 25
            },
            {
                "c": 18,
                "n": "ACOSTA",
                "sT": 0,
                "sEff": 0,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 0,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 1,
                "aEff": 0,
                "aPunto": 0,
                "aPos": 0,
                "aAdm": 1,
                "aNeg": 0,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 0,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {
                    "W2": {
                        "tot": 1,
                        "pt": 0,
                        "err": 0,
                        "orig": 2,
                        "dest": "4"
                    }
                }
            },
            {
                "c": 0,
                "n": "TOTALES EQUIPO",
                "sT": 78,
                "sEff": -5,
                "sPunto": 3,
                "sPos": 13,
                "sVend": 1,
                "sAdm": 13,
                "sNeg": 37,
                "sErr": 11,
                "sOrig": "",
                "sDest": "",
                "rT": 80,
                "rEff": 42,
                "rPunto": 28,
                "rPos": 28,
                "rAdm": 8,
                "rNeg": 6,
                "rVend": 4,
                "rErr": 6,
                "aT": 105,
                "aEff": 13,
                "aPunto": 37,
                "aPos": 7,
                "aAdm": 12,
                "aNeg": 26,
                "aVend": 11,
                "aErr": 12,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 42,
                "bPt": 12,
                "bPtPos": 3,
                "dv4": {
                    "W2": {
                        "tot": 10,
                        "pt": 2,
                        "err": 2,
                        "orig": 2,
                        "dest": "2"
                    },
                    "G4": {
                        "tot": 15,
                        "pt": 6,
                        "err": 0,
                        "orig": 4,
                        "dest": "5"
                    },
                    "W4": {
                        "tot": 36,
                        "pt": 11,
                        "err": 4,
                        "orig": 4,
                        "dest": "5"
                    },
                    "G2": {
                        "tot": 6,
                        "pt": 0,
                        "err": 2,
                        "orig": 2,
                        "dest": "1"
                    },
                    "J1": {
                        "tot": 10,
                        "pt": 5,
                        "err": 0,
                        "orig": 3,
                        "dest": "3"
                    },
                    "Y9": {
                        "tot": 7,
                        "pt": 3,
                        "err": 0,
                        "orig": 9,
                        "dest": "1"
                    },
                    "G8": {
                        "tot": 3,
                        "pt": 1,
                        "err": 1,
                        "orig": 0,
                        "dest": ""
                    },
                    "J4": {
                        "tot": 5,
                        "pt": 2,
                        "err": 1,
                        "orig": 3,
                        "dest": "7"
                    },
                    "G9": {
                        "tot": 4,
                        "pt": 2,
                        "err": 0,
                        "orig": 9,
                        "dest": "4"
                    },
                    "JJ": {
                        "tot": 3,
                        "pt": 2,
                        "err": 0,
                        "orig": 2,
                        "dest": "4"
                    },
                    "Y8": {
                        "tot": 2,
                        "pt": 1,
                        "err": 1,
                        "orig": 8,
                        "dest": "6"
                    },
                    "V3": {
                        "tot": 3,
                        "pt": 1,
                        "err": 1,
                        "orig": 3,
                        "dest": "3"
                    },
                    "W3": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 4,
                        "dest": "2"
                    }
                },
                "bEff": 36
            }
        ]
    },
    {
        "fecha": "16/05/2026",
        "tipo": "P",
        "rival": "Hacoaj",
        "resultado": {
            "casla": 3,
            "rival": 1,
            "sets": [
                "26-24",
                "25-27",
                "25-19",
                "25-22"
            ]
        },
        "jugadores": [
            {
                "c": 2,
                "n": "OJUEZ",
                "sT": 10,
                "sEff": -10,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 1,
                "sNeg": 8,
                "sErr": 1,
                "sOrig": "",
                "sDest": "",
                "rT": 2,
                "rEff": -25,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 1,
                "rNeg": 0,
                "rVend": 1,
                "rErr": 0,
                "aT": 20,
                "aEff": 40,
                "aPunto": 11,
                "aPos": 2,
                "aAdm": 0,
                "aNeg": 4,
                "aVend": 1,
                "aErr": 2,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 13,
                "bPt": 3,
                "bPtPos": 5,
                "dv4": {
                    "J1": {
                        "tot": 12,
                        "pt": 6,
                        "err": 2,
                        "orig": 3,
                        "dest": "5"
                    },
                    "J4": {
                        "tot": 6,
                        "pt": 4,
                        "err": 0,
                        "orig": 3,
                        "dest": "1"
                    },
                    "V3": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 3,
                        "dest": "3"
                    },
                    "J3": {
                        "tot": 1,
                        "pt": 0,
                        "err": 0,
                        "orig": 3,
                        "dest": "6"
                    }
                },
                "bEff": 62
            },
            {
                "c": 3,
                "n": "WINER",
                "sT": 6,
                "sEff": -17,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 1,
                "sNeg": 4,
                "sErr": 1,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 0,
                "aEff": 0,
                "aPunto": 0,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 0,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {}
            },
            {
                "c": 4,
                "n": "VAZQUEZ",
                "sT": 22,
                "sEff": -8,
                "sPunto": 0,
                "sPos": 1,
                "sVend": 0,
                "sAdm": 4,
                "sNeg": 15,
                "sErr": 2,
                "sOrig": "",
                "sDest": "",
                "rT": 1,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 1,
                "rVend": 0,
                "rErr": 0,
                "aT": 5,
                "aEff": 0,
                "aPunto": 1,
                "aPos": 1,
                "aAdm": 0,
                "aNeg": 2,
                "aVend": 1,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 16,
                "bPt": 1,
                "bPtPos": 7,
                "dv4": {
                    "JJ": {
                        "tot": 4,
                        "pt": 1,
                        "err": 0,
                        "orig": 2,
                        "dest": "2"
                    },
                    "G9": {
                        "tot": 1,
                        "pt": 0,
                        "err": 0,
                        "orig": 9,
                        "dest": "5"
                    }
                },
                "bEff": 50
            },
            {
                "c": 5,
                "n": "RAMOS",
                "sT": 5,
                "sEff": -80,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 1,
                "sNeg": 0,
                "sErr": 4,
                "sOrig": "",
                "sDest": "",
                "rT": 1,
                "rEff": 50,
                "rPunto": 0,
                "rPos": 1,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 24,
                "aEff": 33,
                "aPunto": 11,
                "aPos": 1,
                "aAdm": 2,
                "aNeg": 7,
                "aVend": 0,
                "aErr": 3,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 7,
                "bPt": 2,
                "bPtPos": 3,
                "dv4": {
                    "W2": {
                        "tot": 4,
                        "pt": 2,
                        "err": 1,
                        "orig": 2,
                        "dest": "1"
                    },
                    "W4": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 4,
                        "dest": "8"
                    },
                    "Y9": {
                        "tot": 8,
                        "pt": 5,
                        "err": 1,
                        "orig": 9,
                        "dest": "4"
                    },
                    "G2": {
                        "tot": 7,
                        "pt": 3,
                        "err": 1,
                        "orig": 2,
                        "dest": "5"
                    },
                    "G9": {
                        "tot": 2,
                        "pt": 0,
                        "err": 0,
                        "orig": 9,
                        "dest": "5"
                    },
                    "G4": {
                        "tot": 1,
                        "pt": 0,
                        "err": 0,
                        "orig": 4,
                        "dest": "2"
                    },
                    "G3": {
                        "tot": 1,
                        "pt": 0,
                        "err": 0,
                        "orig": 3,
                        "dest": "3"
                    }
                },
                "bEff": 71
            },
            {
                "c": 9,
                "n": "GODOY",
                "sT": 2,
                "sEff": 0,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 2,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 0,
                "aEff": 0,
                "aPunto": 0,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 0,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {}
            },
            {
                "c": 11,
                "n": "DURDOS",
                "sT": 17,
                "sEff": -6,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 5,
                "sNeg": 11,
                "sErr": 1,
                "sOrig": "",
                "sDest": "",
                "rT": 11,
                "rEff": 41,
                "rPunto": 4,
                "rPos": 3,
                "rAdm": 1,
                "rNeg": 1,
                "rVend": 2,
                "rErr": 0,
                "aT": 32,
                "aEff": 25,
                "aPunto": 12,
                "aPos": 4,
                "aAdm": 2,
                "aNeg": 10,
                "aVend": 0,
                "aErr": 4,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 3,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {
                    "W4": {
                        "tot": 17,
                        "pt": 6,
                        "err": 2,
                        "orig": 4,
                        "dest": "7"
                    },
                    "G8": {
                        "tot": 1,
                        "pt": 0,
                        "err": 0,
                        "orig": 8,
                        "dest": "4"
                    },
                    "Y8": {
                        "tot": 4,
                        "pt": 3,
                        "err": 1,
                        "orig": 8,
                        "dest": "3"
                    },
                    "G4": {
                        "tot": 8,
                        "pt": 2,
                        "err": 1,
                        "orig": 4,
                        "dest": "2"
                    },
                    "V3": {
                        "tot": 2,
                        "pt": 1,
                        "err": 0,
                        "orig": 3,
                        "dest": "2"
                    }
                },
                "bEff": 0
            },
            {
                "c": 12,
                "n": "ZANOTTI",
                "sT": 0,
                "sEff": 0,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 0,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 33,
                "rEff": 35,
                "rPunto": 9,
                "rPos": 8,
                "rAdm": 10,
                "rNeg": 4,
                "rVend": 1,
                "rErr": 1,
                "aT": 0,
                "aEff": 0,
                "aPunto": 0,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 0,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {}
            },
            {
                "c": 14,
                "n": "NIELSON",
                "sT": 16,
                "sEff": 17,
                "sPunto": 2,
                "sPos": 1,
                "sVend": 1,
                "sAdm": 3,
                "sNeg": 9,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 27,
                "rEff": 59,
                "rPunto": 9,
                "rPos": 14,
                "rAdm": 4,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 40,
                "aEff": 30,
                "aPunto": 18,
                "aPos": 2,
                "aAdm": 3,
                "aNeg": 11,
                "aVend": 0,
                "aErr": 6,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 15,
                "bPt": 2,
                "bPtPos": 5,
                "dv4": {
                    "W4": {
                        "tot": 19,
                        "pt": 10,
                        "err": 1,
                        "orig": 4,
                        "dest": "2"
                    },
                    "G4": {
                        "tot": 15,
                        "pt": 7,
                        "err": 3,
                        "orig": 4,
                        "dest": "1"
                    },
                    "W2": {
                        "tot": 3,
                        "pt": 1,
                        "err": 0,
                        "orig": 2,
                        "dest": "4"
                    },
                    "G2": {
                        "tot": 2,
                        "pt": 0,
                        "err": 1,
                        "orig": 2,
                        "dest": "4"
                    },
                    "Y8": {
                        "tot": 1,
                        "pt": 0,
                        "err": 1,
                        "orig": 0,
                        "dest": ""
                    }
                },
                "bEff": 47
            },
            {
                "c": 15,
                "n": "ROTEZZI",
                "sT": 13,
                "sEff": -8,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 2,
                "sNeg": 10,
                "sErr": 1,
                "sOrig": "",
                "sDest": "",
                "rT": 6,
                "rEff": 8,
                "rPunto": 0,
                "rPos": 3,
                "rAdm": 2,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 1,
                "aT": 11,
                "aEff": 45,
                "aPunto": 5,
                "aPos": 2,
                "aAdm": 1,
                "aNeg": 3,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 5,
                "bPt": 0,
                "bPtPos": 2,
                "dv4": {
                    "J4": {
                        "tot": 6,
                        "pt": 2,
                        "err": 0,
                        "orig": 3,
                        "dest": "1"
                    },
                    "V3": {
                        "tot": 2,
                        "pt": 1,
                        "err": 0,
                        "orig": 3,
                        "dest": "3"
                    },
                    "J1": {
                        "tot": 3,
                        "pt": 2,
                        "err": 0,
                        "orig": 3,
                        "dest": "7"
                    }
                },
                "bEff": 40
            },
            {
                "c": 18,
                "n": "ACOSTA",
                "sT": 9,
                "sEff": 11,
                "sPunto": 2,
                "sPos": 2,
                "sVend": 1,
                "sAdm": 1,
                "sNeg": 1,
                "sErr": 2,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 16,
                "aEff": 25,
                "aPunto": 8,
                "aPos": 1,
                "aAdm": 1,
                "aNeg": 2,
                "aVend": 1,
                "aErr": 3,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 3,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {
                    "G2": {
                        "tot": 3,
                        "pt": 1,
                        "err": 0,
                        "orig": 2,
                        "dest": "4"
                    },
                    "Y9": {
                        "tot": 9,
                        "pt": 4,
                        "err": 3,
                        "orig": 9,
                        "dest": "1"
                    },
                    "W2": {
                        "tot": 3,
                        "pt": 2,
                        "err": 0,
                        "orig": 2,
                        "dest": "4"
                    },
                    "G9": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 9,
                        "dest": "4"
                    }
                },
                "bEff": 0
            },
            {
                "c": 0,
                "n": "TOTALES EQUIPO",
                "sT": 100,
                "sEff": -6,
                "sPunto": 4,
                "sPos": 4,
                "sVend": 2,
                "sAdm": 18,
                "sNeg": 60,
                "sErr": 12,
                "sOrig": "",
                "sDest": "",
                "rT": 81,
                "rEff": 40,
                "rPunto": 22,
                "rPos": 29,
                "rAdm": 18,
                "rNeg": 6,
                "rVend": 4,
                "rErr": 2,
                "aT": 148,
                "aEff": 30,
                "aPunto": 66,
                "aPos": 13,
                "aAdm": 9,
                "aNeg": 39,
                "aVend": 3,
                "aErr": 18,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 62,
                "bPt": 8,
                "bPtPos": 22,
                "dv4": {
                    "W2": {
                        "tot": 10,
                        "pt": 5,
                        "err": 1,
                        "orig": 2,
                        "dest": "1"
                    },
                    "W4": {
                        "tot": 37,
                        "pt": 17,
                        "err": 3,
                        "orig": 4,
                        "dest": "8"
                    },
                    "J1": {
                        "tot": 15,
                        "pt": 8,
                        "err": 2,
                        "orig": 3,
                        "dest": "5"
                    },
                    "Y9": {
                        "tot": 17,
                        "pt": 9,
                        "err": 4,
                        "orig": 9,
                        "dest": "4"
                    },
                    "G4": {
                        "tot": 24,
                        "pt": 9,
                        "err": 4,
                        "orig": 4,
                        "dest": "1"
                    },
                    "G2": {
                        "tot": 12,
                        "pt": 4,
                        "err": 2,
                        "orig": 2,
                        "dest": "5"
                    },
                    "G8": {
                        "tot": 1,
                        "pt": 0,
                        "err": 0,
                        "orig": 8,
                        "dest": "4"
                    },
                    "JJ": {
                        "tot": 4,
                        "pt": 1,
                        "err": 0,
                        "orig": 2,
                        "dest": "2"
                    },
                    "G9": {
                        "tot": 4,
                        "pt": 1,
                        "err": 0,
                        "orig": 9,
                        "dest": "5"
                    },
                    "Y8": {
                        "tot": 5,
                        "pt": 3,
                        "err": 2,
                        "orig": 8,
                        "dest": "3"
                    },
                    "J4": {
                        "tot": 12,
                        "pt": 6,
                        "err": 0,
                        "orig": 3,
                        "dest": "1"
                    },
                    "G3": {
                        "tot": 1,
                        "pt": 0,
                        "err": 0,
                        "orig": 3,
                        "dest": "3"
                    },
                    "V3": {
                        "tot": 5,
                        "pt": 3,
                        "err": 0,
                        "orig": 3,
                        "dest": "3"
                    },
                    "J3": {
                        "tot": 1,
                        "pt": 0,
                        "err": 0,
                        "orig": 3,
                        "dest": "6"
                    }
                },
                "bEff": 48
            }
        ]
    },
    {
        "fecha": "22/05/2026",
        "tipo": "P",
        "rival": "Vélez",
        "resultado": {
            "casla": 3,
            "rival": 2,
            "sets": [
                "23-25",
                "21-25",
                "25-18",
                "25-22",
                "15-8"
            ]
        },
        "jugadores": [
            {
                "c": 2,
                "n": "OJUEZ",
                "sT": 8,
                "sEff": -9,
                "sPunto": 0,
                "sPos": 1,
                "sVend": 0,
                "sAdm": 1,
                "sNeg": 5,
                "sErr": 1,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 15,
                "aEff": 33,
                "aPunto": 7,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 6,
                "aVend": 0,
                "aErr": 2,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 10,
                "bPt": 4,
                "bPtPos": 3,
                "dv4": {
                    "J4": {
                        "tot": 4,
                        "pt": 1,
                        "err": 1,
                        "orig": 3,
                        "dest": "1"
                    },
                    "JJ": {
                        "tot": 1,
                        "pt": 0,
                        "err": 1,
                        "orig": 0,
                        "dest": ""
                    },
                    "J2": {
                        "tot": 5,
                        "pt": 3,
                        "err": 0,
                        "orig": 3,
                        "dest": "5"
                    },
                    "J3": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 3,
                        "dest": "9"
                    },
                    "J1": {
                        "tot": 4,
                        "pt": 2,
                        "err": 0,
                        "orig": 3,
                        "dest": "5"
                    }
                },
                "bEff": 70
            },
            {
                "c": 4,
                "n": "VAZQUEZ",
                "sT": 30,
                "sEff": 19,
                "sPunto": 5,
                "sPos": 3,
                "sVend": 2,
                "sAdm": 1,
                "sNeg": 18,
                "sErr": 1,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 1,
                "aEff": -100,
                "aPunto": 0,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 1,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 3,
                "bPt": 0,
                "bPtPos": 1,
                "dv4": {
                    "JJ": {
                        "tot": 1,
                        "pt": 0,
                        "err": 0,
                        "orig": 2,
                        "dest": "4"
                    }
                },
                "bEff": 33
            },
            {
                "c": 5,
                "n": "RAMOS",
                "sT": 1,
                "sEff": 0,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 1,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 5,
                "aEff": 40,
                "aPunto": 2,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 3,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 3,
                "bPt": 1,
                "bPtPos": 0,
                "dv4": {
                    "W2": {
                        "tot": 3,
                        "pt": 1,
                        "err": 0,
                        "orig": 2,
                        "dest": "1"
                    },
                    "Y9": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 9,
                        "dest": "5"
                    },
                    "G2": {
                        "tot": 1,
                        "pt": 0,
                        "err": 0,
                        "orig": 2,
                        "dest": "8"
                    }
                },
                "bEff": 33
            },
            {
                "c": 6,
                "n": "VILLARRUEL",
                "sT": 5,
                "sEff": -15,
                "sPunto": 0,
                "sPos": 1,
                "sVend": 0,
                "sAdm": 1,
                "sNeg": 2,
                "sErr": 1,
                "sOrig": "",
                "sDest": "",
                "rT": 3,
                "rEff": 67,
                "rPunto": 2,
                "rPos": 0,
                "rAdm": 1,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 5,
                "aEff": -20,
                "aPunto": 1,
                "aPos": 1,
                "aAdm": 1,
                "aNeg": 0,
                "aVend": 1,
                "aErr": 1,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 0,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {
                    "W4": {
                        "tot": 5,
                        "pt": 1,
                        "err": 1,
                        "orig": 4,
                        "dest": "1"
                    }
                }
            },
            {
                "c": 9,
                "n": "GODOY",
                "sT": 2,
                "sEff": 12,
                "sPunto": 0,
                "sPos": 1,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 1,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 2,
                "aEff": 50,
                "aPunto": 1,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 1,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 5,
                "bPt": 0,
                "bPtPos": 1,
                "dv4": {
                    "JJ": {
                        "tot": 1,
                        "pt": 0,
                        "err": 0,
                        "orig": 2,
                        "dest": "4"
                    },
                    "V3": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 3,
                        "dest": "3"
                    }
                },
                "bEff": 20
            },
            {
                "c": 11,
                "n": "DURDOS",
                "sT": 6,
                "sEff": -50,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 1,
                "sNeg": 2,
                "sErr": 3,
                "sOrig": "",
                "sDest": "",
                "rT": 34,
                "rEff": 31,
                "rPunto": 5,
                "rPos": 13,
                "rAdm": 10,
                "rNeg": 4,
                "rVend": 2,
                "rErr": 0,
                "aT": 31,
                "aEff": 6,
                "aPunto": 11,
                "aPos": 2,
                "aAdm": 3,
                "aNeg": 6,
                "aVend": 5,
                "aErr": 4,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 5,
                "bPt": 0,
                "bPtPos": 1,
                "dv4": {
                    "W4": {
                        "tot": 20,
                        "pt": 9,
                        "err": 3,
                        "orig": 4,
                        "dest": "2"
                    },
                    "G4": {
                        "tot": 8,
                        "pt": 2,
                        "err": 0,
                        "orig": 4,
                        "dest": "2"
                    },
                    "Y8": {
                        "tot": 3,
                        "pt": 0,
                        "err": 1,
                        "orig": 8,
                        "dest": "1"
                    }
                },
                "bEff": 20
            },
            {
                "c": 12,
                "n": "ZANOTTI",
                "sT": 0,
                "sEff": 0,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 0,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 16,
                "rEff": 31,
                "rPunto": 4,
                "rPos": 6,
                "rAdm": 2,
                "rNeg": 2,
                "rVend": 0,
                "rErr": 2,
                "aT": 0,
                "aEff": 0,
                "aPunto": 0,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 0,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {}
            },
            {
                "c": 14,
                "n": "NIELSON",
                "sT": 19,
                "sEff": 7,
                "sPunto": 1,
                "sPos": 3,
                "sVend": 1,
                "sAdm": 7,
                "sNeg": 6,
                "sErr": 1,
                "sOrig": "",
                "sDest": "",
                "rT": 33,
                "rEff": 50,
                "rPunto": 14,
                "rPos": 7,
                "rAdm": 6,
                "rNeg": 5,
                "rVend": 0,
                "rErr": 1,
                "aT": 33,
                "aEff": 45,
                "aPunto": 17,
                "aPos": 1,
                "aAdm": 4,
                "aNeg": 9,
                "aVend": 1,
                "aErr": 1,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 6,
                "bPt": 1,
                "bPtPos": 1,
                "dv4": {
                    "W4": {
                        "tot": 24,
                        "pt": 13,
                        "err": 1,
                        "orig": 4,
                        "dest": "1"
                    },
                    "G4": {
                        "tot": 9,
                        "pt": 4,
                        "err": 0,
                        "orig": 4,
                        "dest": "1"
                    }
                },
                "bEff": 33
            },
            {
                "c": 17,
                "n": "HERBSOMMER",
                "sT": 22,
                "sEff": 6,
                "sPunto": 0,
                "sPos": 3,
                "sVend": 3,
                "sAdm": 2,
                "sNeg": 13,
                "sErr": 1,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 22,
                "aEff": 55,
                "aPunto": 13,
                "aPos": 2,
                "aAdm": 3,
                "aNeg": 3,
                "aVend": 1,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 15,
                "bPt": 3,
                "bPtPos": 3,
                "dv4": {
                    "J2": {
                        "tot": 5,
                        "pt": 2,
                        "err": 0,
                        "orig": 3,
                        "dest": "3"
                    },
                    "J4": {
                        "tot": 13,
                        "pt": 8,
                        "err": 0,
                        "orig": 3,
                        "dest": "3"
                    },
                    "J1": {
                        "tot": 4,
                        "pt": 3,
                        "err": 0,
                        "orig": 3,
                        "dest": "1"
                    }
                },
                "bEff": 40
            },
            {
                "c": 18,
                "n": "ACOSTA",
                "sT": 12,
                "sEff": -31,
                "sPunto": 1,
                "sPos": 1,
                "sVend": 0,
                "sAdm": 2,
                "sNeg": 3,
                "sErr": 5,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 30,
                "aEff": 30,
                "aPunto": 15,
                "aPos": 1,
                "aAdm": 2,
                "aNeg": 6,
                "aVend": 3,
                "aErr": 3,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 4,
                "bPt": 1,
                "bPtPos": 1,
                "dv4": {
                    "Y9": {
                        "tot": 9,
                        "pt": 6,
                        "err": 2,
                        "orig": 9,
                        "dest": "1"
                    },
                    "W2": {
                        "tot": 12,
                        "pt": 7,
                        "err": 0,
                        "orig": 2,
                        "dest": "9"
                    },
                    "G2": {
                        "tot": 6,
                        "pt": 1,
                        "err": 1,
                        "orig": 2,
                        "dest": "4"
                    },
                    "G9": {
                        "tot": 2,
                        "pt": 0,
                        "err": 0,
                        "orig": 9,
                        "dest": "4"
                    },
                    "V3": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 0,
                        "dest": ""
                    }
                },
                "bEff": 50
            },
            {
                "c": 19,
                "n": "DIAZ BOLLI",
                "sT": 4,
                "sEff": 12,
                "sPunto": 0,
                "sPos": 2,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 2,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 0,
                "aEff": 0,
                "aPunto": 0,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 0,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {}
            },
            {
                "c": 0,
                "n": "TOTALES EQUIPO",
                "sT": 109,
                "sEff": 1,
                "sPunto": 7,
                "sPos": 15,
                "sVend": 6,
                "sAdm": 15,
                "sNeg": 53,
                "sErr": 13,
                "sOrig": "",
                "sDest": "",
                "rT": 86,
                "rEff": 40,
                "rPunto": 25,
                "rPos": 26,
                "rAdm": 19,
                "rNeg": 11,
                "rVend": 2,
                "rErr": 3,
                "aT": 144,
                "aEff": 31,
                "aPunto": 67,
                "aPos": 7,
                "aAdm": 13,
                "aNeg": 34,
                "aVend": 12,
                "aErr": 11,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 51,
                "bPt": 10,
                "bPtPos": 11,
                "dv4": {
                    "Y9": {
                        "tot": 10,
                        "pt": 7,
                        "err": 2,
                        "orig": 9,
                        "dest": "1"
                    },
                    "W4": {
                        "tot": 49,
                        "pt": 23,
                        "err": 5,
                        "orig": 4,
                        "dest": "2"
                    },
                    "J2": {
                        "tot": 10,
                        "pt": 5,
                        "err": 0,
                        "orig": 3,
                        "dest": "3"
                    },
                    "G4": {
                        "tot": 17,
                        "pt": 6,
                        "err": 0,
                        "orig": 4,
                        "dest": "2"
                    },
                    "W2": {
                        "tot": 15,
                        "pt": 8,
                        "err": 0,
                        "orig": 2,
                        "dest": "9"
                    },
                    "G2": {
                        "tot": 7,
                        "pt": 1,
                        "err": 1,
                        "orig": 2,
                        "dest": "4"
                    },
                    "Y8": {
                        "tot": 3,
                        "pt": 0,
                        "err": 1,
                        "orig": 8,
                        "dest": "1"
                    },
                    "J4": {
                        "tot": 17,
                        "pt": 9,
                        "err": 1,
                        "orig": 3,
                        "dest": "3"
                    },
                    "J1": {
                        "tot": 8,
                        "pt": 5,
                        "err": 0,
                        "orig": 3,
                        "dest": "1"
                    },
                    "JJ": {
                        "tot": 3,
                        "pt": 0,
                        "err": 1,
                        "orig": 2,
                        "dest": "4"
                    },
                    "G9": {
                        "tot": 2,
                        "pt": 0,
                        "err": 0,
                        "orig": 9,
                        "dest": "4"
                    },
                    "J3": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 3,
                        "dest": "9"
                    },
                    "V3": {
                        "tot": 2,
                        "pt": 2,
                        "err": 0,
                        "orig": 3,
                        "dest": "3"
                    }
                },
                "bEff": 41
            }
        ]
    }
]
};
