window.HISTORIAL_DATA = {
  "generado": "24/05/2026 14:47:10",
  "entrenamientos": [
    {
        "fecha": "22/05/2026",
        "tipo": "P",
        "rival": "Velez Sarsfield",
        "resultado": {
            "casla": 3,
            "rival": 2,
            "sets": [
                "23-25",
                "21-25",
                "25-18",
                "25-22",
                "15-8"
            ]
        },
        "jugadores": [
            {
                "c": 2,
                "n": "OJUEZ",
                "sT": 8,
                "sEff": 0,
                "sPunto": 1,
                "sPos": 1,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 5,
                "sErr": 1,
                "sOrig": "6",
                "sDest": "5",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 15,
                "aEff": 33,
                "aPunto": 7,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 6,
                "aVend": 0,
                "aErr": 2,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 10,
                "bPt": 5,
                "bPtPos": 3,
                "dv4": {
                    "J4": {
                        "tot": 4,
                        "pt": 1,
                        "err": 1,
                        "orig": 3,
                        "dest": "1"
                    },
                    "JJ": {
                        "tot": 1,
                        "pt": 0,
                        "err": 1,
                        "orig": 0,
                        "dest": ""
                    },
                    "J2": {
                        "tot": 5,
                        "pt": 3,
                        "err": 0,
                        "orig": 3,
                        "dest": "5"
                    },
                    "J3": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 3,
                        "dest": "9"
                    },
                    "J1": {
                        "tot": 4,
                        "pt": 2,
                        "err": 0,
                        "orig": 3,
                        "dest": "5"
                    }
                }
            },
            {
                "c": 4,
                "n": "VAZQUEZ",
                "sT": 30,
                "sEff": 17,
                "sPunto": 6,
                "sPos": 3,
                "sVend": 2,
                "sAdm": 0,
                "sNeg": 18,
                "sErr": 1,
                "sOrig": "5",
                "sDest": "6",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 1,
                "aEff": -100,
                "aPunto": 0,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 1,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 3,
                "bPt": 0,
                "bPtPos": 1,
                "dv4": {
                    "JJ": {
                        "tot": 1,
                        "pt": 0,
                        "err": 0,
                        "orig": 2,
                        "dest": "4"
                    }
                }
            },
            {
                "c": 5,
                "n": "RAMOS",
                "sT": 1,
                "sEff": 0,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 1,
                "sErr": 0,
                "sOrig": "1",
                "sDest": "7",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 5,
                "aEff": 40,
                "aPunto": 2,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 3,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 3,
                "bPt": 2,
                "bPtPos": 0,
                "dv4": {
                    "W2": {
                        "tot": 3,
                        "pt": 1,
                        "err": 0,
                        "orig": 2,
                        "dest": "1"
                    },
                    "Y9": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 9,
                        "dest": "5"
                    },
                    "G2": {
                        "tot": 1,
                        "pt": 0,
                        "err": 0,
                        "orig": 2,
                        "dest": "8"
                    }
                }
            },
            {
                "c": 6,
                "n": "VILLARRUEL",
                "sT": 5,
                "sEff": 0,
                "sPunto": 1,
                "sPos": 1,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 2,
                "sErr": 1,
                "sOrig": "6",
                "sDest": "6",
                "rT": 3,
                "rEff": 100,
                "rPunto": 3,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 5,
                "aEff": 0,
                "aPunto": 2,
                "aPos": 1,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 1,
                "aErr": 1,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 0,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {
                    "W4": {
                        "tot": 5,
                        "pt": 2,
                        "err": 1,
                        "orig": 4,
                        "dest": "1"
                    }
                }
            },
            {
                "c": 9,
                "n": "GODOY",
                "sT": 2,
                "sEff": 0,
                "sPunto": 0,
                "sPos": 1,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 1,
                "sErr": 0,
                "sOrig": "1",
                "sDest": "8",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 2,
                "aEff": 50,
                "aPunto": 1,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 1,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 5,
                "bPt": 2,
                "bPtPos": 1,
                "dv4": {
                    "JJ": {
                        "tot": 1,
                        "pt": 0,
                        "err": 0,
                        "orig": 2,
                        "dest": "4"
                    },
                    "V3": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 3,
                        "dest": "3"
                    }
                }
            },
            {
                "c": 11,
                "n": "DURDOS",
                "sT": 6,
                "sEff": -33,
                "sPunto": 1,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 2,
                "sErr": 3,
                "sOrig": "6",
                "sDest": "6",
                "rT": 34,
                "rEff": 100,
                "rPunto": 15,
                "rPos": 13,
                "rAdm": 0,
                "rNeg": 4,
                "rVend": 2,
                "rErr": 0,
                "aT": 31,
                "aEff": 16,
                "aPunto": 14,
                "aPos": 2,
                "aAdm": 0,
                "aNeg": 6,
                "aVend": 5,
                "aErr": 4,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 5,
                "bPt": 2,
                "bPtPos": 1,
                "dv4": {
                    "W4": {
                        "tot": 20,
                        "pt": 11,
                        "err": 3,
                        "orig": 4,
                        "dest": "2"
                    },
                    "G4": {
                        "tot": 8,
                        "pt": 3,
                        "err": 0,
                        "orig": 4,
                        "dest": "2"
                    },
                    "Y8": {
                        "tot": 3,
                        "pt": 0,
                        "err": 1,
                        "orig": 8,
                        "dest": "1"
                    }
                }
            },
            {
                "c": 12,
                "n": "ZANOTTI",
                "sT": 0,
                "sEff": 0,
                "sPunto": 0,
                "sPos": 0,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 0,
                "sErr": 0,
                "sOrig": "",
                "sDest": "",
                "rT": 16,
                "rEff": 100,
                "rPunto": 6,
                "rPos": 6,
                "rAdm": 0,
                "rNeg": 2,
                "rVend": 0,
                "rErr": 2,
                "aT": 0,
                "aEff": 0,
                "aPunto": 0,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 0,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {}
            },
            {
                "c": 14,
                "n": "NIELSON",
                "sT": 19,
                "sEff": 37,
                "sPunto": 8,
                "sPos": 3,
                "sVend": 1,
                "sAdm": 0,
                "sNeg": 6,
                "sErr": 1,
                "sOrig": "1",
                "sDest": "1",
                "rT": 33,
                "rEff": 100,
                "rPunto": 20,
                "rPos": 7,
                "rAdm": 0,
                "rNeg": 5,
                "rVend": 0,
                "rErr": 1,
                "aT": 33,
                "aEff": 58,
                "aPunto": 21,
                "aPos": 1,
                "aAdm": 0,
                "aNeg": 9,
                "aVend": 1,
                "aErr": 1,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 6,
                "bPt": 2,
                "bPtPos": 1,
                "dv4": {
                    "W4": {
                        "tot": 24,
                        "pt": 16,
                        "err": 1,
                        "orig": 4,
                        "dest": "1"
                    },
                    "G4": {
                        "tot": 9,
                        "pt": 5,
                        "err": 0,
                        "orig": 4,
                        "dest": "1"
                    }
                }
            },
            {
                "c": 17,
                "n": "HERBSOMMER",
                "sT": 22,
                "sEff": 5,
                "sPunto": 2,
                "sPos": 3,
                "sVend": 3,
                "sAdm": 0,
                "sNeg": 13,
                "sErr": 1,
                "sOrig": "5",
                "sDest": "5",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 22,
                "aEff": 68,
                "aPunto": 16,
                "aPos": 2,
                "aAdm": 0,
                "aNeg": 3,
                "aVend": 1,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 15,
                "bPt": 5,
                "bPtPos": 3,
                "dv4": {
                    "J2": {
                        "tot": 5,
                        "pt": 3,
                        "err": 0,
                        "orig": 3,
                        "dest": "3"
                    },
                    "J4": {
                        "tot": 13,
                        "pt": 10,
                        "err": 0,
                        "orig": 3,
                        "dest": "3"
                    },
                    "J1": {
                        "tot": 4,
                        "pt": 3,
                        "err": 0,
                        "orig": 3,
                        "dest": "1"
                    }
                }
            },
            {
                "c": 18,
                "n": "ACOSTA",
                "sT": 12,
                "sEff": -17,
                "sPunto": 3,
                "sPos": 1,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 3,
                "sErr": 5,
                "sOrig": "1",
                "sDest": "5",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 30,
                "aEff": 37,
                "aPunto": 17,
                "aPos": 1,
                "aAdm": 0,
                "aNeg": 6,
                "aVend": 3,
                "aErr": 3,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 4,
                "bPt": 2,
                "bPtPos": 1,
                "dv4": {
                    "Y9": {
                        "tot": 9,
                        "pt": 6,
                        "err": 2,
                        "orig": 9,
                        "dest": "1"
                    },
                    "W2": {
                        "tot": 12,
                        "pt": 8,
                        "err": 0,
                        "orig": 2,
                        "dest": "9"
                    },
                    "G2": {
                        "tot": 6,
                        "pt": 2,
                        "err": 1,
                        "orig": 2,
                        "dest": "4"
                    },
                    "G9": {
                        "tot": 2,
                        "pt": 0,
                        "err": 0,
                        "orig": 9,
                        "dest": "4"
                    },
                    "V3": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 0,
                        "dest": ""
                    }
                }
            },
            {
                "c": 19,
                "n": "DIAZ BOLLI",
                "sT": 4,
                "sEff": 0,
                "sPunto": 0,
                "sPos": 2,
                "sVend": 0,
                "sAdm": 0,
                "sNeg": 2,
                "sErr": 0,
                "sOrig": "5",
                "sDest": "6",
                "rT": 0,
                "rEff": 0,
                "rPunto": 0,
                "rPos": 0,
                "rAdm": 0,
                "rNeg": 0,
                "rVend": 0,
                "rErr": 0,
                "aT": 0,
                "aEff": 0,
                "aPunto": 0,
                "aPos": 0,
                "aAdm": 0,
                "aNeg": 0,
                "aVend": 0,
                "aErr": 0,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 0,
                "bPt": 0,
                "bPtPos": 0,
                "dv4": {}
            },
            {
                "c": 0,
                "n": "TOTALES EQUIPO",
                "sT": 109,
                "sEff": 8,
                "sPunto": 22,
                "sPos": 15,
                "sVend": 6,
                "sAdm": 0,
                "sNeg": 53,
                "sErr": 13,
                "sOrig": "5",
                "sDest": "6",
                "rT": 86,
                "rEff": 100,
                "rPunto": 44,
                "rPos": 26,
                "rAdm": 0,
                "rNeg": 11,
                "rVend": 2,
                "rErr": 3,
                "aT": 144,
                "aEff": 40,
                "aPunto": 80,
                "aPos": 7,
                "aAdm": 0,
                "aNeg": 34,
                "aVend": 12,
                "aErr": 11,
                "aTCQ": 0,
                "aEffAlta": 0,
                "bT": 51,
                "bPt": 20,
                "bPtPos": 11,
                "dv4": {
                    "Y9": {
                        "tot": 10,
                        "pt": 7,
                        "err": 2,
                        "orig": 9,
                        "dest": "1"
                    },
                    "W4": {
                        "tot": 49,
                        "pt": 29,
                        "err": 5,
                        "orig": 4,
                        "dest": "2"
                    },
                    "J2": {
                        "tot": 10,
                        "pt": 6,
                        "err": 0,
                        "orig": 3,
                        "dest": "3"
                    },
                    "G4": {
                        "tot": 17,
                        "pt": 8,
                        "err": 0,
                        "orig": 4,
                        "dest": "2"
                    },
                    "W2": {
                        "tot": 15,
                        "pt": 9,
                        "err": 0,
                        "orig": 2,
                        "dest": "9"
                    },
                    "G2": {
                        "tot": 7,
                        "pt": 2,
                        "err": 1,
                        "orig": 2,
                        "dest": "4"
                    },
                    "Y8": {
                        "tot": 3,
                        "pt": 0,
                        "err": 1,
                        "orig": 8,
                        "dest": "1"
                    },
                    "J4": {
                        "tot": 17,
                        "pt": 11,
                        "err": 1,
                        "orig": 3,
                        "dest": "3"
                    },
                    "J1": {
                        "tot": 8,
                        "pt": 5,
                        "err": 0,
                        "orig": 3,
                        "dest": "1"
                    },
                    "JJ": {
                        "tot": 3,
                        "pt": 0,
                        "err": 1,
                        "orig": 2,
                        "dest": "4"
                    },
                    "G9": {
                        "tot": 2,
                        "pt": 0,
                        "err": 0,
                        "orig": 9,
                        "dest": "4"
                    },
                    "J3": {
                        "tot": 1,
                        "pt": 1,
                        "err": 0,
                        "orig": 3,
                        "dest": "9"
                    },
                    "V3": {
                        "tot": 2,
                        "pt": 2,
                        "err": 0,
                        "orig": 3,
                        "dest": "3"
                    }
                }
            }
        ]
    }
]
}};
