window.GAMEPLAN_DATA = {
  "rival": "LOMAS",
  "torneo": "División de Honor 2026",
  "fecha": 6,
  "generado": "28/05/2026 15:07",
  "jugadores": [
  ],
  "armador": {
    "titular": {"nombre":"","rotaciones":[{"pos":"P1","total":0,"dist":[{"zona":4,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":3,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":2,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":6,"tot":0,"pts":0,"pct":0,"pct_p":0}]},{"pos":"P6","total":0,"dist":[{"zona":4,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":3,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":2,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":6,"tot":0,"pts":0,"pct":0,"pct_p":0}]},{"pos":"P5","total":0,"dist":[{"zona":4,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":3,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":2,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":6,"tot":0,"pts":0,"pct":0,"pct_p":0}]},{"pos":"P4","total":0,"dist":[{"zona":4,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":3,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":2,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":6,"tot":0,"pts":0,"pct":0,"pct_p":0}]},{"pos":"P3","total":0,"dist":[{"zona":4,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":3,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":2,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":6,"tot":0,"pts":0,"pct":0,"pct_p":0}]},{"pos":"P2","total":0,"dist":[{"zona":4,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":3,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":2,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":6,"tot":0,"pts":0,"pct":0,"pct_p":0}]}],"pills":[{"label":"P1","eff":0,"tot":0,"pts":0,"pts_pct":0,"err_pct":0},{"label":"P6","eff":0,"tot":0,"pts":0,"pts_pct":0,"err_pct":0},{"label":"P5","eff":0,"tot":0,"pts":0,"pts_pct":0,"err_pct":0},{"label":"P4","eff":0,"tot":0,"pts":0,"pts_pct":0,"err_pct":0},{"label":"P3","eff":0,"tot":0,"pts":0,"pts_pct":0,"err_pct":0},{"label":"P2","eff":0,"tot":0,"pts":0,"pts_pct":0,"err_pct":0},{"label":"SO","eff":0,"tot":0,"pts":0,"pts_pct":0,"err_pct":0},{"label":"TR","eff":0,"tot":0,"pts":0,"pts_pct":0,"err_pct":0}],"recepcion":[{"label":"SO","eff":0},{"label":"REC #","eff":0},{"label":"REC +","eff":0},{"label":"REC !","eff":0},{"label":"REC -","eff":0},{"label":"TRANS","eff":0}],"so":{"label":"SO","total":0,"dist":[{"zona":4,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":3,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":2,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":8,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":9,"tot":0,"pts":0,"pct":0,"pct_p":0}]},"tr":{"label":"TR","total":0,"dist":[{"zona":4,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":3,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":2,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":8,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":9,"tot":0,"pts":0,"pct":0,"pct_p":0}]}},
    "suplente": {"nombre":"","rotaciones":[{"pos":"P1","total":0,"dist":[{"zona":4,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":3,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":2,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":6,"tot":0,"pts":0,"pct":0,"pct_p":0}]},{"pos":"P6","total":0,"dist":[{"zona":4,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":3,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":2,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":6,"tot":0,"pts":0,"pct":0,"pct_p":0}]},{"pos":"P5","total":0,"dist":[{"zona":4,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":3,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":2,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":6,"tot":0,"pts":0,"pct":0,"pct_p":0}]},{"pos":"P4","total":0,"dist":[{"zona":4,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":3,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":2,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":6,"tot":0,"pts":0,"pct":0,"pct_p":0}]},{"pos":"P3","total":0,"dist":[{"zona":4,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":3,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":2,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":6,"tot":0,"pts":0,"pct":0,"pct_p":0}]},{"pos":"P2","total":0,"dist":[{"zona":4,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":3,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":2,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":6,"tot":0,"pts":0,"pct":0,"pct_p":0}]}],"pills":[{"label":"P1","eff":0,"tot":0,"pts":0,"pts_pct":0,"err_pct":0},{"label":"P6","eff":0,"tot":0,"pts":0,"pts_pct":0,"err_pct":0},{"label":"P5","eff":0,"tot":0,"pts":0,"pts_pct":0,"err_pct":0},{"label":"P4","eff":0,"tot":0,"pts":0,"pts_pct":0,"err_pct":0},{"label":"P3","eff":0,"tot":0,"pts":0,"pts_pct":0,"err_pct":0},{"label":"P2","eff":0,"tot":0,"pts":0,"pts_pct":0,"err_pct":0},{"label":"SO","eff":0,"tot":0,"pts":0,"pts_pct":0,"err_pct":0},{"label":"TR","eff":0,"tot":0,"pts":0,"pts_pct":0,"err_pct":0}],"recepcion":[{"label":"SO","eff":0},{"label":"REC #","eff":0},{"label":"REC +","eff":0},{"label":"REC !","eff":0},{"label":"REC -","eff":0},{"label":"TRANS","eff":0}],"so":{"label":"SO","total":0,"dist":[{"zona":4,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":3,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":2,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":8,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":9,"tot":0,"pts":0,"pct":0,"pct_p":0}]},"tr":{"label":"TR","total":0,"dist":[{"zona":4,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":3,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":2,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":8,"tot":0,"pts":0,"pct":0,"pct_p":0},{"zona":9,"tot":0,"pts":0,"pct":0,"pct_p":0}]}}
  }
};
