// game_plans.js — generado automáticamente por generar_datos_partidos.py
const GAME_PLANS = [
  {
    rival:     'UNTREF',
    torneo:    'División de Honor',
    fecha:     '01/05/2026',
    horario:   '',
    condicion: 'LOCAL',
    archivo:   'game_plan_untref.html',
    resultado: {'casla': 3, 'rival': 1},
  },
  {
    rival:     'CIUDAD',
    torneo:    'División de Honor',
    fecha:     '05/05/2026',
    horario:   '',
    condicion: 'LOCAL',
    archivo:   'game_plan_ciudad.html',
    resultado: null,
  },
  {
    rival:     'FERRO',
    torneo:    'División de Honor',
    fecha:     '08/05/2026',
    horario:   '',
    condicion: 'LOCAL',
    archivo:   'game_plan_ferro.html',
    resultado: {'casla': 1, 'rival': 3},
  },
  {
    rival:     'HACOAJ',
    torneo:    'División de Honor',
    fecha:     '16/05/2026',
    horario:   '',
    condicion: 'LOCAL',
    archivo:   'game_plan_hacoaj.html',
    resultado: {'casla': 3, 'rival': 1},
  },
  {
    rival:     'VELEZ',
    torneo:    'División de Honor',
    fecha:     '22/05/2026',
    horario:   '',
    condicion: 'LOCAL',
    archivo:   'game_plan_velez.html',
    resultado: {'casla': 3, 'rival': 2},
  },
  {
    rival:     'DBANF',
    torneo:    'División de Honor',
    fecha:     '26/05/2026',
    horario:   '',
    condicion: 'LOCAL',
    archivo:   'game_plan_dbanf.html',
    resultado: {'casla': 2, 'rival': 3},
  },
  {
    rival:     'LOMAS',
    torneo:    'División de Honor',
    fecha:     '30/05/2026',
    horario:   '',
    condicion: 'LOCAL',
    archivo:   'game_plan_lomas.html',
    resultado: {'casla': 3, 'rival': 2},
  },
];
