// ═══════════════════════════════════════════════════════
// CASLA VOLEY — Módulo de Idiomas
// Español (ES) · English (EN) · Deutsch (DE)
// ═══════════════════════════════════════════════════════
const TRADUCCIONES = {
  "ES": {
    "hub": "HUB",
    "panel_vivo": "Panel en Vivo",
    "scout_vivo": "Scout en Vivo",
    "cargar": "Cargar",
    "historial": "Historial",
    "game_plan": "Plan de Juego",
    "videos": "Videos",
    "volver": "← Volver",
    "inicio": "↑",
    "sistema_analisis": "Sistema de Análisis",
    "acceso_rapido": "Acceso rápido",
    "prox_partido": "Próximo partido",
    "calendario": "Calendario",
    "estado_sistema": "Estado del sistema",
    "operativo": "Operativo",
    "en_desarrollo": "En desarrollo",
    "ver_analisis": "Ver análisis →",
    "en_vivo": "En vivo",
    "todos": "Todos",
    "recepcion": "Recepción",
    "saque": "Saque",
    "ataque": "Ataque",
    "bloqueo": "Bloqueo",
    "comb": "Combinación",
    "tipo": "Tipo",
    "ver_cancha": "📍 Ver en cancha",
    "sin_datos": "Sin datos",
    "periodo": "Período",
    "todo": "Todo",
    "dias_7": "7 días",
    "mes": "Mes",
    "trimestre": "Trimestre",
    "entrenamientos": "Entrenamientos",
    "partidos": "Partidos",
    "equipo": "Equipo",
    "individual": "Individual",
    "comparar": "Comparar",
    "sesiones": "Sesiones",
    "acciones": "Acciones",
    "stats_equipo": "STATS DEL EQUIPO — ÚLTIMA SESIÓN",
    "stats_acum": "STATS ACUMULADOS",
    "sin_datos_msg": "Sin datos registrados",
    "registro_sesion": "REGISTRO POR SESIÓN",
    "fecha": "Fecha",
    "jugador": "Jugador",
    "analisis_tactico": "Análisis táctico de rivales",
    "como_vamos": "CÓMO VAMOS A JUGAR",
    "analisis_armador": "ANÁLISIS DEL ARMADOR RIVAL",
    "plan_saque": "🏐 PLAN DE SAQUE",
    "recep_sistema": "🛡 RECEPCIÓN Y SISTEMA",
    "ataque_propio": "⚡ ATAQUE PROPIO",
    "analisis_rival": "🔍 ANÁLISIS DEL RIVAL",
    "imagenes": "🖼️ IMÁGENES DE REFERENCIA",
    "pts_fuertes": "✅ PUNTOS FUERTES",
    "pts_debiles": "❌ PUNTOS DÉBILES",
    "comentarios": "COMENTARIOS GENERALES",
    "estrategia": "ESTRATEGIA Y NOTAS TÁCTICAS",
    "distribucion_rot": "DISTRIBUCIÓN POR ROTACIÓN",
    "opuesto": "OPUESTO",
    "central": "CENTRAL",
    "punta": "PUNTA",
    "armador": "ARMADOR",
    "libero": "LÍBERO",
    "ver_video": "Ver video",
    "ej_EJ002": "Banco Plano",
    "ej_EJ003": "Banco Plano + Rechazo Escapular",
    "ej_EJ004": "Banco Plano + Flexiones alternadas con Medicine Ball",
    "ej_EJ005": "Banco Plano + Flexiones de Brazo con Peso",
    "ej_EJ006": "Banco Plano + Apertura con mancuerna",
    "ej_EJ007": "Apertura con Mancuerna",
    "ej_EJ008": "Banco Inclinado",
    "ej_EJ009": "Banco Inclinado + Apertura Inclinado",
    "ej_EJ010": "Apertura Inclinado con Mancuerna",
    "ej_EJ011": "Cruce con Cables",
    "ej_EJ012": "Elevación con Mancuerna",
    "ej_EJ013": "Dominadas Agarre Abierto",
    "ej_EJ014": "Dominadas Agarre Supino (Cerrado)",
    "ej_EJ015": "Dominadas Agarre Neutral",
    "ej_EJ016": "Tirones de Espalda Agarre Abierto - Polea",
    "ej_EJ017": "Tirones de Espalda Supino (Cerrado) - Polea",
    "ej_EJ018": "Tiron de Espalda Abierto + Cerrado - Polea",
    "ej_EJ019": "Remo Espalda  - Polea",
    "ej_EJ020": "Remo Espalda  Abierto - Maquina",
    "ej_EJ021": "Remo Abierto de Espalda Sentado Abierto + Cerrado",
    "ej_EJ022": "Serrucho con Mancuerna",
    "ej_EJ023": "Barra T Inclinada",
    "ej_EJ024": "Vuelta al Mundo",
    "ej_EJ025": "Vuelos Frontales con Disco",
    "ej_EJ026": "Vuelos Frontales con Mancuerna",
    "ej_EJ027": "Vuelos posteriores",
    "ej_EJ028": "Press Arnold",
    "ej_EJ029": "Press Arnold + Vuelos laterales",
    "ej_EJ030": "Press Arnold + Movimiento en 8",
    "ej_EJ031": "Press Arnold + Golpe de Manos Altas con Medicine Ball",
    "ej_EJ032": "Press de Hombros con Mancuerna",
    "ej_EJ033": "Press de Hombros + Tirar Medicine Ball vs Pared",
    "ej_EJ034": "Press de Hombros + Vuelta al Mundo",
    "ej_EJ035": "Sentadilla Profunda",
    "ej_EJ036": "Sentadilla Explosiva",
    "ej_EJ037": "Sentadilla con transferencia - Saltos desde sentado",
    "ej_EJ038": "Sentadilla con transferencia + Estocadas Posteriores cruzadas",
    "ej_EJ039": "Sentadilla Frontal",
    "ej_EJ040": "Sentadilla Sumo con Mancuerna",
    "ej_EJ041": "Sentadilla Sumo + Subidas al Banco Lateral",
    "ej_EJ042": "Sentadilla Bulgara con Mancuerna",
    "ej_EJ043": "Sentadilla Bulgara con Salto",
    "ej_EJ044": "Sentadilla Bulgara + Subidas al banco",
    "ej_EJ045": "Snatch con Mancuerna + Sentadilla Profunda",
    "ej_EJ046": "Cargada de parado",
    "ej_EJ047": "Cargada de parado con transferencia - Saltos al cajón",
    "ej_EJ048": "Cargada de parado con transferencia - Drop Jump",
    "ej_EJ049": "Cargada de parado con transferencia - Desplazamiento de bloqueo + Salto al cajón",
    "ej_EJ050": "Cargada a una mano con mancuerna",
    "ej_EJ051": "Split Jerk con Landmine - Barra",
    "ej_EJ052": "Split Jerk con Mancuerna",
    "ej_EJ053": "Hip Trust con barra",
    "ej_EJ054": "Saltos Skater",
    "ej_EJ055": "Estocada posterior cruzada",
    "ej_EJ056": "Estocada posterior cruzada con mancuerna",
    "ej_EJ057": "Estocadas frontal con mancuerna",
    "ej_EJ058": "Subidas al banco - lateral",
    "ej_EJ059": "Prensa",
    "ej_EJ060": "Camilla de Cuadriceps",
    "ej_EJ061": "Camilla de Isquitibiales",
    "ej_EJ062": "Gemelos en Maquina",
    "ej_EJ063": "Biceps Martillo",
    "ej_EJ064": "Biceps Invertido",
    "ej_EJ065": "Biceps Estricto",
    "ej_EJ066": "Biceps con Rotación",
    "ej_EJ067": "Biceps con Rotación + Martillo",
    "ej_EJ068": "Biceps Barra W",
    "ej_EJ069": "Triceps Trasnuca con Mancuerna",
    "ej_EJ070": "Triceps Polea Invertido",
    "ej_EJ071": "Triceps Polea con Soga",
    "ej_EJ072": "Triceps Polea",
    "ej_EJ073": "Triceps Polea (Barra) + Invertido",
    "ej_EJ074": "Fondos",
    "ej_EJ075": "Abdominales cortos con piernas en el aire",
    "ej_EJ076": "Abdominales cortos",
    "ej_EJ077": "Abdominales sentado con Peso",
    "ej_EJ078": "Abdominales cortos laterales",
    "ej_EJ079": "Abdominales bicicleta",
    "ej_EJ080": "Abdominales Sentado con Giro y peso",
    "ej_EJ081": "Abdominales Estiro y Recojo",
    "ej_EJ082": "Abdominales Twist Sovietico con peso",
    "ej_EJ083": "Abdominales Tijera",
    "ej_EJ084": "Abdominales V alternados",
    "ej_EJ085": "Bicho Muerto con Peso",
    "ej_EJ086": "Landmine Twist",
    "ej_EJ087": "Press Paloff Isometrico",
    "ej_EJ088": "Press Paloff con Rotación",
    "ej_EJ089": "Plancha Fontal",
    "ej_EJ090": "Plancha Frontal Superman",
    "ej_EJ091": "Plancha Frontal con 1 Pierna en el Aire",
    "ej_EJ092": "Plancha Frontal Dinámica - Twist",
    "ej_EJ093": "Planfha Frontal Dinámica - De Baja a Alta",
    "ej_EJ094": "Plancha Lateral",
    "ej_EJ095": "Plancha lateral con movimiento Arriba y Abajo",
    "ej_EJ096": "Plancha Lateral con Rotación",
    "ej_EJ097": "Plancha Copenhagen",
    "ej_EJ098": "Abdominales Rueda",
    "ej_EJ099": "Espinales estrictos",
    "ej_EJ100": "Espinales isométricos",
    "ej_EJ101": "Espinales con bastón - Estiro y Recojo",
    "ej_EJ102": "Espinales alternados",
    "ej_EJ103": "Espinales W",
    "ej_EJ104": "Espinales Nado Corto",
    "ej_EJ105": "Espinales con Rotación - Limpiaparabrizas",
    "ej_EJ106": "Espinales Superman en Cuadrupedia",
    "ej_EJ107": "Espinales en banco inclinado - Isometrico",
    "ej_EJ108": "Espinales en banco inclinado con peso",
    "ej_EJ109": "Hombro - Movimiento en 8",
    "ej_EJ110": "Hombro - Rotación Interna y Externa con banda",
    "ej_EJ111": "Cadera - Puente de Cadera Isometric",
    "ej_EJ112": "Espalda - Gato Contento / Gato Enojado",
    "ej_EJ113": "Rodilla - Sentadilla Isometrica en Pared",
    "ej_EJ114": "Rodilla - Sentadilla Española",
    "ej_EJ115": "Tobillo - Mobilidad con Banda en Posición Repartida",
    "ej_EJ116": "Cadera - Mobilidad 90-90 con elevación",
    "ej_EJ117": "Completo - Gran Estiramiento con Rotación",
    "ej_EJ118": "Camilla de Cuadriceps Exentrica",
    "ej_EJ119": "Camilla de Izquitibial - Exentrica",
    "ej_EJ120": "Puente de cadera a 1 pierna",
    "ej_EJ121": "Sentadilla dinamica en pared con Pelota",
    "ej_EJ122": "Equilibrio en bosu",
    "ej_EJ123": "Core - Bicho Muerto Isometrico",
    "ej_EJ124": "Espalda Baja - Espinales 45° Isometrico",
    "prep_fisica": "Preparación Física",
    "prep_fisica_sub": "Rutinas personalizadas por jugador",
    "selecciona_jugador": "Seleccioná tu nombre para ver tu rutina",
    "sin_rutina": "Sin rutina cargada",
    "sin_rutina_desc": "El profe todavía no cargó la rutina para este jugador.",
    "registra_peso": "Registrá tu peso por serie (kg)",
    "tu_observacion": "💬 Tu observación",
    "obs_placeholder": "Cómo te sentiste, si subiste peso, dolor, etc...",
    "indicacion_profe": "📋 Indicación del profe",
    "calc_titulo": "Calculadora de Carga",
    "calc_sub": "1RM & Progresión",
    "calc_peso": "Peso levantado (kg)",
    "calc_reps": "Repeticiones",
    "calc_formula": "Fórmula",
    "calc_btn": "CALCULAR 1RM Y PROGRESIÓN",
    "series": "SERIES",
    "descanso": "DESCANSO",
    "cargado": "✓ CARGADO",
    "dev_banner": "Sección en desarrollo activo · Los datos se guardan en este dispositivo",
    "semanas": "Semanas",
    "ejercicios_count": "ejercicios",
    "registros_count": "Registros"
  },
  "EN": {
    "hub": "HUB",
    "panel_vivo": "Live Panel",
    "scout_vivo": "Live Scout",
    "cargar": "Load",
    "historial": "History",
    "game_plan": "Game Plan",
    "videos": "Videos",
    "volver": "← Back",
    "inicio": "↑",
    "sistema_analisis": "Analytics System",
    "acceso_rapido": "Quick access",
    "prox_partido": "Next match",
    "calendario": "Schedule",
    "estado_sistema": "System status",
    "operativo": "Active",
    "en_desarrollo": "In development",
    "ver_analisis": "View analysis →",
    "en_vivo": "Live",
    "todos": "All",
    "recepcion": "Reception",
    "saque": "Serve",
    "ataque": "Attack",
    "bloqueo": "Block",
    "comb": "Combination",
    "tipo": "Type",
    "ver_cancha": "📍 View on court",
    "sin_datos": "No data",
    "periodo": "Period",
    "todo": "All time",
    "dias_7": "7 days",
    "mes": "Month",
    "trimestre": "Quarter",
    "entrenamientos": "Practices",
    "partidos": "Matches",
    "equipo": "Team",
    "individual": "Individual",
    "comparar": "Compare",
    "sesiones": "Sessions",
    "acciones": "Actions",
    "stats_equipo": "TEAM STATS — LAST SESSION",
    "stats_acum": "ACCUMULATED STATS",
    "sin_datos_msg": "No data recorded",
    "registro_sesion": "SESSION LOG",
    "fecha": "Date",
    "jugador": "Player",
    "analisis_tactico": "Opponent tactical analysis",
    "como_vamos": "GAME STRATEGY",
    "analisis_armador": "OPPONENT SETTER ANALYSIS",
    "plan_saque": "🏐 SERVE PLAN",
    "recep_sistema": "🛡 RECEPTION & SYSTEM",
    "ataque_propio": "⚡ OWN ATTACK",
    "analisis_rival": "🔍 OPPONENT ANALYSIS",
    "imagenes": "🖼️ REFERENCE IMAGES",
    "pts_fuertes": "✅ STRENGTHS",
    "pts_debiles": "❌ WEAKNESSES",
    "comentarios": "GENERAL COMMENTS",
    "estrategia": "STRATEGY & TACTICAL NOTES",
    "distribucion_rot": "DISTRIBUTION BY ROTATION",
    "opuesto": "OPPOSITE",
    "central": "MIDDLE",
    "punta": "OUTSIDE",
    "armador": "SETTER",
    "libero": "LIBERO",
    "ver_video": "Watch video",
    "ej_EJ002": "Bench press",
    "ej_EJ003": "Bench press + Scapular rejection (floor)",
    "ej_EJ004": "Bench press + Push up alternated with Medicine Ball",
    "ej_EJ005": "Bench press + Push Up with Weight",
    "ej_EJ006": "Bench press + Chest Dumbbell Fly",
    "ej_EJ007": "Chest Dumbbell Fly",
    "ej_EJ008": "Inclined Chest Press",
    "ej_EJ009": "Inclined Chest Press + Incline Chest Dumbbell Flies",
    "ej_EJ010": "Incline Chest Dumbbell Flies",
    "ej_EJ011": "Chest cable row",
    "ej_EJ012": "Chest Elevations",
    "ej_EJ013": "Pull Ups - Open Grip",
    "ej_EJ014": "Pull Ups - Close Grip",
    "ej_EJ015": "Pull Ups - Neutral Grip",
    "ej_EJ016": "Lat Pull Down - Open Grip",
    "ej_EJ017": "Lat Pull Down - Inverse Grip - Supino",
    "ej_EJ018": "Lat Pull Down - Open Grip + Close Grip",
    "ej_EJ019": "Back Cable Row",
    "ej_EJ020": "Back Seated High Row",
    "ej_EJ021": "Back Seated Row Open + Close",
    "ej_EJ022": "Dumbell Row",
    "ej_EJ023": "Inclined T Bar Row for back",
    "ej_EJ024": "Around the World - Shoulder",
    "ej_EJ025": "Front Plate Raises",
    "ej_EJ026": "Frontal Flies  (shoulder)",
    "ej_EJ027": "Posterior Flies (shoulder)",
    "ej_EJ028": "Press Arnold",
    "ej_EJ029": "Press Arnold + Lateral Flies",
    "ej_EJ030": "Press Arnold + 8 movement w/lightweight",
    "ej_EJ031": "press arnold + high pass with med. Ball",
    "ej_EJ032": "Shoulder Press",
    "ej_EJ033": "Shoulder press + medicine ball throw to floor",
    "ej_EJ034": "Shoulder press + Around the World - Shoulder",
    "ej_EJ035": "Back Squat",
    "ej_EJ036": "Explosive Back Squats (using calves at the end)",
    "ej_EJ037": "Back Squat + jump from seated",
    "ej_EJ038": "Back Squat + Cross-Recerse Lunges",
    "ej_EJ039": "Front Squat",
    "ej_EJ040": "Sumo Squat with dumbell",
    "ej_EJ041": "Sumo Squat + Box Lateral Step up",
    "ej_EJ042": "Bulgarian Squat",
    "ej_EJ043": "Bulgarian Squat with jump",
    "ej_EJ044": "Bulgarian Squat + Box step up",
    "ej_EJ045": "Dumbbell Snatch + Squat",
    "ej_EJ046": "Hang power clean",
    "ej_EJ047": "Hang power Clean + box jump",
    "ej_EJ048": "Hang power clean + drop jump (low altitud)",
    "ej_EJ049": "Hang power clean + lateral shuffle and box jump",
    "ej_EJ050": "Dumbbell One Arm Hang Power Clean",
    "ej_EJ051": "Landmine Split Jerk",
    "ej_EJ052": "Dumbbell Split Jerk",
    "ej_EJ053": "Hip Trust with bar",
    "ej_EJ054": "Skater",
    "ej_EJ055": "Cross-Reverse Lunges",
    "ej_EJ056": "Dumbbell Cross-Reverse Lunges",
    "ej_EJ057": "Dumbell Lunge",
    "ej_EJ058": "Lateral Box Step-Ups",
    "ej_EJ059": "Leg Press",
    "ej_EJ060": "Leg Extensions",
    "ej_EJ061": "Hamstring Curls",
    "ej_EJ062": "Calf Raises Machine",
    "ej_EJ063": "Biceps - Hammer Curl",
    "ej_EJ064": "Biceps - Inverted Curl",
    "ej_EJ065": "Biceps Curl",
    "ej_EJ066": "Rotating Biceps Curl",
    "ej_EJ067": "Rotating Biceps Cur + Hammer",
    "ej_EJ068": "Biceps W Bar (EZ)",
    "ej_EJ069": "Dumbbell Overhead Triceps Extension",
    "ej_EJ070": "Reverse Grip Triceps Pulldown",
    "ej_EJ071": "Rope Cable Triceps Pulldown",
    "ej_EJ072": "Triceps pulldown",
    "ej_EJ073": "Triceps pulldown + Inverted",
    "ej_EJ074": "Triceps Dips",
    "ej_EJ075": "Crunches crossed with legs in the air",
    "ej_EJ076": "Regular Crunches",
    "ej_EJ077": "Sit Ups Crunches with Weight",
    "ej_EJ078": "Lateral Crunches",
    "ej_EJ079": "Bicicle Crunch",
    "ej_EJ080": "Sit Up Twist With Weight",
    "ej_EJ081": "Tuck Crunches / In-and-Outs",
    "ej_EJ082": "Russian Twist With Weight",
    "ej_EJ083": "Scissor Abs",
    "ej_EJ084": "Alternate V-ups (abs)",
    "ej_EJ085": "Weighted Dead Bug",
    "ej_EJ086": "Landmine Twist",
    "ej_EJ087": "Paloff Press Hold",
    "ej_EJ088": "Paloff Press with Rotation",
    "ej_EJ089": "Frontal Plank",
    "ej_EJ090": "Front Plank - Superman",
    "ej_EJ091": "Front Plank With 1 Leg Lifted",
    "ej_EJ092": "DynamicTwist  Front Plank",
    "ej_EJ093": "Dynamic Up and Down Front Plank",
    "ej_EJ094": "Side Plank Isometric",
    "ej_EJ095": "Side Plank - Up and Down",
    "ej_EJ096": "Side Plank with Rotation",
    "ej_EJ097": "Copenhagen Plank",
    "ej_EJ098": "Abs Roll Out",
    "ej_EJ099": "Floor Back Extensions - all in one",
    "ej_EJ100": "Floor Back extensions isometric",
    "ej_EJ101": "Floor Back Extensions - With Stick",
    "ej_EJ102": "Floor Back Extensions - Alternating",
    "ej_EJ103": "Floor Back Extensions - W Shape",
    "ej_EJ104": "Floor Back Extensions - Short Swimmers",
    "ej_EJ105": "Floor Back Rotations (Windshield)",
    "ej_EJ106": "Alternated Superman In 4 Legs",
    "ej_EJ107": "Incline Back Extension Isometric Hold",
    "ej_EJ108": "Incline Back Extension",
    "ej_EJ109": "Shoulder - 8 movement with light Weight",
    "ej_EJ110": "Shoulder - Internal / External Rotation with band",
    "ej_EJ111": "Glute Bridge Isometric",
    "ej_EJ112": "Cat / Cow",
    "ej_EJ113": "Isometric Wall Squat",
    "ej_EJ114": "Spanish Squat",
    "ej_EJ115": "Ankle Mobility with band",
    "ej_EJ116": "Hip - Hip Mobility 90-90 with elevation",
    "ej_EJ117": "Greatest Streach with Thoracic Rotation",
    "ej_EJ118": "Leg Extension Machine – Eccentric Quadriceps",
    "ej_EJ119": "Hamstring Curl Machine – Eccentric Hamstrings",
    "ej_EJ120": "Unilateral Hip Bridge (Glute Bridge)",
    "ej_EJ121": "Wall Squat with Exercise Ball (Dynamic)",
    "ej_EJ122": "Single‑Leg Balance on Unstable Surface (BOSU)",
    "ej_EJ123": "Isometric Dead Bug",
    "ej_EJ124": "Isometric Back Extensions 45°",
    "prep_fisica": "Physical Training",
    "prep_fisica_sub": "Personalized routines per player",
    "selecciona_jugador": "Select your name to see your routine",
    "sin_rutina": "No routine loaded",
    "sin_rutina_desc": "The coach hasn't loaded a routine for this player yet.",
    "registra_peso": "Log your weight per set (kg)",
    "tu_observacion": "💬 Your note",
    "obs_placeholder": "How you felt, if you increased weight, pain, etc...",
    "indicacion_profe": "📋 Coach's note",
    "calc_titulo": "Load Calculator",
    "calc_sub": "1RM & Progression",
    "calc_peso": "Weight lifted (kg)",
    "calc_reps": "Repetitions",
    "calc_formula": "Formula",
    "calc_btn": "CALCULATE 1RM & PROGRESSION",
    "series": "SETS",
    "descanso": "REST",
    "cargado": "✓ LOGGED",
    "dev_banner": "Section in active development · Data is saved on this device",
    "semanas": "Weeks",
    "ejercicios_count": "exercises",
    "registros_count": "Logs"
  },
  "DE": {
    "hub": "HUB",
    "panel_vivo": "Live-Panel",
    "historial": "Verlauf",
    "game_plan": "Spielplan",
    "videos": "Videos",
    "volver": "← Zurück",
    "inicio": "↑",
    "sistema_analisis": "Analysesystem",
    "acceso_rapido": "Schnellzugriff",
    "prox_partido": "Nächstes Spiel",
    "calendario": "Spielplan",
    "estado_sistema": "Systemstatus",
    "operativo": "Aktiv",
    "en_desarrollo": "In Entwicklung",
    "ver_analisis": "Analyse anzeigen →",
    "en_vivo": "Live",
    "todos": "Alle",
    "recepcion": "Annahme",
    "saque": "Aufschlag",
    "ataque": "Angriff",
    "bloqueo": "Block",
    "comb": "Kombination",
    "tipo": "Typ",
    "ver_cancha": "📍 Auf Feld anzeigen",
    "sin_datos": "Keine Daten",
    "periodo": "Zeitraum",
    "todo": "Gesamt",
    "dias_7": "7 Tage",
    "mes": "Monat",
    "trimestre": "Quartal",
    "entrenamientos": "Training",
    "partidos": "Spiele",
    "equipo": "Team",
    "individual": "Individuell",
    "comparar": "Vergleichen",
    "sesiones": "Einheiten",
    "acciones": "Aktionen",
    "stats_equipo": "TEAM-STATS — LETZTE EINHEIT",
    "stats_acum": "KUMULIERTE STATS",
    "sin_datos_msg": "Keine Daten erfasst",
    "registro_sesion": "EINHEITENPROTOKOLL",
    "fecha": "Datum",
    "jugador": "Spieler",
    "analisis_tactico": "Taktische Gegneranalyse",
    "como_vamos": "SPIELSTRATEGIE",
    "analisis_armador": "GEGNER-ZUSPIELER-ANALYSE",
    "plan_saque": "🏐 AUFSCHLAGPLAN",
    "recep_sistema": "🛡 ANNAHME & SYSTEM",
    "ataque_propio": "⚡ EIGENER ANGRIFF",
    "analisis_rival": "🔍 GEGNERANALYSE",
    "imagenes": "🖼️ REFERENZBILDER",
    "pts_fuertes": "✅ STÄRKEN",
    "pts_debiles": "❌ SCHWÄCHEN",
    "comentarios": "ALLGEMEINE KOMMENTARE",
    "estrategia": "STRATEGIE & TAKTISCHE NOTIZEN",
    "distribucion_rot": "VERTEILUNG NACH ROTATION",
    "opuesto": "DIAGONAL",
    "central": "MITTE",
    "punta": "AUSSEN",
    "armador": "ZUSPIELER",
    "libero": "LIBERO",
    "ver_video": "Video ansehen",
    "ej_EJ002": "Bench press",
    "ej_EJ003": "Bench press + Scapular rejection (floor)",
    "ej_EJ004": "Bench press + Push up alternated with Medicine Ball",
    "ej_EJ005": "Bench press + Push Up with Weight",
    "ej_EJ006": "Bench press + Chest Dumbbell Fly",
    "ej_EJ007": "Chest Dumbbell Fly",
    "ej_EJ008": "Inclined Chest Press",
    "ej_EJ009": "Inclined Chest Press + Incline Chest Dumbbell Flies",
    "ej_EJ010": "Incline Chest Dumbbell Flies",
    "ej_EJ011": "Chest cable row",
    "ej_EJ012": "Chest Elevations",
    "ej_EJ013": "Pull Ups - Open Grip",
    "ej_EJ014": "Pull Ups - Close Grip",
    "ej_EJ015": "Pull Ups - Neutral Grip",
    "ej_EJ016": "Lat Pull Down - Open Grip",
    "ej_EJ017": "Lat Pull Down - Inverse Grip - Supino",
    "ej_EJ018": "Lat Pull Down - Open Grip + Close Grip",
    "ej_EJ019": "Back Cable Row",
    "ej_EJ020": "Back Seated High Row",
    "ej_EJ021": "Back Seated Row Open + Close",
    "ej_EJ022": "Dumbell Row",
    "ej_EJ023": "Inclined T Bar Row for back",
    "ej_EJ024": "Around the World - Shoulder",
    "ej_EJ025": "Front Plate Raises",
    "ej_EJ026": "Frontal Flies  (shoulder)",
    "ej_EJ027": "Posterior Flies (shoulder)",
    "ej_EJ028": "Press Arnold",
    "ej_EJ029": "Press Arnold + Lateral Flies",
    "ej_EJ030": "Press Arnold + 8 movement w/lightweight",
    "ej_EJ031": "press arnold + high pass with med. Ball",
    "ej_EJ032": "Shoulder Press",
    "ej_EJ033": "Shoulder press + medicine ball throw to floor",
    "ej_EJ034": "Shoulder press + Around the World - Shoulder",
    "ej_EJ035": "Back Squat",
    "ej_EJ036": "Explosive Back Squats (using calves at the end)",
    "ej_EJ037": "Back Squat + jump from seated",
    "ej_EJ038": "Back Squat + Cross-Recerse Lunges",
    "ej_EJ039": "Front Squat",
    "ej_EJ040": "Sumo Squat with dumbell",
    "ej_EJ041": "Sumo Squat + Box Lateral Step up",
    "ej_EJ042": "Bulgarian Squat",
    "ej_EJ043": "Bulgarian Squat with jump",
    "ej_EJ044": "Bulgarian Squat + Box step up",
    "ej_EJ045": "Dumbbell Snatch + Squat",
    "ej_EJ046": "Hang power clean",
    "ej_EJ047": "Hang power Clean + box jump",
    "ej_EJ048": "Hang power clean + drop jump (low altitud)",
    "ej_EJ049": "Hang power clean + lateral shuffle and box jump",
    "ej_EJ050": "Dumbbell One Arm Hang Power Clean",
    "ej_EJ051": "Landmine Split Jerk",
    "ej_EJ052": "Dumbbell Split Jerk",
    "ej_EJ053": "Hip Trust with bar",
    "ej_EJ054": "Skater",
    "ej_EJ055": "Cross-Reverse Lunges",
    "ej_EJ056": "Dumbbell Cross-Reverse Lunges",
    "ej_EJ057": "Dumbell Lunge",
    "ej_EJ058": "Lateral Box Step-Ups",
    "ej_EJ059": "Leg Press",
    "ej_EJ060": "Leg Extensions",
    "ej_EJ061": "Hamstring Curls",
    "ej_EJ062": "Calf Raises Machine",
    "ej_EJ063": "Biceps - Hammer Curl",
    "ej_EJ064": "Biceps - Inverted Curl",
    "ej_EJ065": "Biceps Curl",
    "ej_EJ066": "Rotating Biceps Curl",
    "ej_EJ067": "Rotating Biceps Cur + Hammer",
    "ej_EJ068": "Biceps W Bar (EZ)",
    "ej_EJ069": "Dumbbell Overhead Triceps Extension",
    "ej_EJ070": "Reverse Grip Triceps Pulldown",
    "ej_EJ071": "Rope Cable Triceps Pulldown",
    "ej_EJ072": "Triceps pulldown",
    "ej_EJ073": "Triceps pulldown + Inverted",
    "ej_EJ074": "Triceps Dips",
    "ej_EJ075": "Crunches crossed with legs in the air",
    "ej_EJ076": "Regular Crunches",
    "ej_EJ077": "Sit Ups Crunches with Weight",
    "ej_EJ078": "Lateral Crunches",
    "ej_EJ079": "Bicicle Crunch",
    "ej_EJ080": "Sit Up Twist With Weight",
    "ej_EJ081": "Tuck Crunches / In-and-Outs",
    "ej_EJ082": "Russian Twist With Weight",
    "ej_EJ083": "Scissor Abs",
    "ej_EJ084": "Alternate V-ups (abs)",
    "ej_EJ085": "Weighted Dead Bug",
    "ej_EJ086": "Landmine Twist",
    "ej_EJ087": "Paloff Press Hold",
    "ej_EJ088": "Paloff Press with Rotation",
    "ej_EJ089": "Frontal Plank",
    "ej_EJ090": "Front Plank - Superman",
    "ej_EJ091": "Front Plank With 1 Leg Lifted",
    "ej_EJ092": "DynamicTwist  Front Plank",
    "ej_EJ093": "Dynamic Up and Down Front Plank",
    "ej_EJ094": "Side Plank Isometric",
    "ej_EJ095": "Side Plank - Up and Down",
    "ej_EJ096": "Side Plank with Rotation",
    "ej_EJ097": "Copenhagen Plank",
    "ej_EJ098": "Abs Roll Out",
    "ej_EJ099": "Floor Back Extensions - all in one",
    "ej_EJ100": "Floor Back extensions isometric",
    "ej_EJ101": "Floor Back Extensions - With Stick",
    "ej_EJ102": "Floor Back Extensions - Alternating",
    "ej_EJ103": "Floor Back Extensions - W Shape",
    "ej_EJ104": "Floor Back Extensions - Short Swimmers",
    "ej_EJ105": "Floor Back Rotations (Windshield)",
    "ej_EJ106": "Alternated Superman In 4 Legs",
    "ej_EJ107": "Incline Back Extension Isometric Hold",
    "ej_EJ108": "Incline Back Extension",
    "ej_EJ109": "Shoulder - 8 movement with light Weight",
    "ej_EJ110": "Shoulder - Internal / External Rotation with band",
    "ej_EJ111": "Glute Bridge Isometric",
    "ej_EJ112": "Cat / Cow",
    "ej_EJ113": "Isometric Wall Squat",
    "ej_EJ114": "Spanish Squat",
    "ej_EJ115": "Ankle Mobility with band",
    "ej_EJ116": "Hip - Hip Mobility 90-90 with elevation",
    "ej_EJ117": "Greatest Streach with Thoracic Rotation",
    "ej_EJ118": "Leg Extension Machine – Eccentric Quadriceps",
    "ej_EJ119": "Hamstring Curl Machine – Eccentric Hamstrings",
    "ej_EJ120": "Unilateral Hip Bridge (Glute Bridge)",
    "ej_EJ121": "Wall Squat with Exercise Ball (Dynamic)",
    "ej_EJ122": "Single‑Leg Balance on Unstable Surface (BOSU)",
    "ej_EJ123": "Isometric Dead Bug",
    "ej_EJ124": "Isometric Back Extensions 45°",
    "prep_fisica": "Körperliche Vorbereitung",
    "prep_fisica_sub": "Personalisierte Routinen pro Spieler",
    "selecciona_jugador": "Wähle deinen Namen, um deine Routine zu sehen",
    "sin_rutina": "Keine Routine geladen",
    "sin_rutina_desc": "Der Trainer hat noch keine Routine für diesen Spieler geladen.",
    "registra_peso": "Gewicht pro Satz eintragen (kg)",
    "tu_observacion": "💬 Deine Notiz",
    "obs_placeholder": "Wie du dich gefühlt hast, ob du mehr Gewicht genommen hast, Schmerzen, etc...",
    "indicacion_profe": "📋 Trainerhinweis",
    "calc_titulo": "Belastungsrechner",
    "calc_sub": "1WM & Progression",
    "calc_peso": "Gehobenes Gewicht (kg)",
    "calc_reps": "Wiederholungen",
    "calc_formula": "Formel",
    "calc_btn": "1WM & PROGRESSION BERECHNEN",
    "series": "SÄTZE",
    "descanso": "PAUSE",
    "cargado": "✓ EINGETRAGEN",
    "dev_banner": "Abschnitt in aktiver Entwicklung · Daten werden auf diesem Gerät gespeichert",
    "semanas": "Wochen",
    "ejercicios_count": "Übungen",
    "registros_count": "Einträge"
  }
};

var idiomaActual = localStorage.getItem('casla_lang') || 'ES';

function t(key){
  var tr = TRADUCCIONES[idiomaActual];
  return (tr && tr[key]) ? tr[key] : (TRADUCCIONES['ES'][key] || key);
}

function setIdioma(lang){
  idiomaActual = lang;
  localStorage.setItem('casla_lang', lang);
  document.querySelectorAll('[data-t]').forEach(function(el){
    var key = el.getAttribute('data-t');
    el.textContent = t(key);
  });
  document.querySelectorAll('[data-t-ph]').forEach(function(el){
    el.placeholder = t(el.getAttribute('data-t-ph'));
  });
  document.querySelectorAll('.lang-btn').forEach(function(b){
    b.classList.toggle('on', b.dataset.lang === lang);
    b.style.background = b.dataset.lang === lang ? 'rgba(232,25,44,.15)' : 'rgba(255,255,255,.03)';
    b.style.color = b.dataset.lang === lang ? '#e8192c' : '#64748b';
  });
  document.dispatchEvent(new CustomEvent('langChange', {detail: lang}));
}

function renderLangSelector(){
  var wrap = document.createElement('div');
  wrap.style.cssText = 'display:flex;align-items:center;gap:4px';
  ['ES','EN','DE'].forEach(function(lang){
    var btn = document.createElement('button');
    btn.className = 'lang-btn' + (lang === idiomaActual ? ' on' : '');
    btn.dataset.lang = lang;
    btn.textContent = lang;
    btn.style.cssText = 'padding:4px 9px;border-radius:6px;border:1px solid rgba(255,255,255,.1);'
      + 'background:' + (lang===idiomaActual?'rgba(232,25,44,.15)':'rgba(255,255,255,.03)') + ';'
      + 'color:' + (lang===idiomaActual?'#e8192c':'#64748b') + ';'
      + 'font-family:Barlow Condensed,sans-serif;font-size:10px;font-weight:800;'
      + 'letter-spacing:1.5px;cursor:pointer;transition:all .15s';
    btn.addEventListener('click', function(){ setIdioma(lang); });
    btn.addEventListener('mouseover', function(){
      if(lang!==idiomaActual) this.style.color='#e2e8f0';
    });
    btn.addEventListener('mouseout', function(){
      if(lang!==idiomaActual) this.style.color='#64748b';
    });
    wrap.appendChild(btn);
  });
  return wrap;
}

document.addEventListener('DOMContentLoaded', function(){
  var langWrap = document.getElementById('lang-wrap');
  if(langWrap) langWrap.appendChild(renderLangSelector());
  setIdioma(idiomaActual);
});
